import type { FlockOperatorDescriptor } from './flockOperatorTypes';
import { enumParam, integerParam, numberParam, port, vecParam } from './flockParamBuilders';

const behaviorOutput = [port('behavior', 'Behavior', 'behavior')];
const selectionInput = port('selection', 'Selection', 'selection');
const falloff = enumParam('falloff', 'Falloff', 'smooth', ['none', 'linear', 'smooth', 'inverse'], 'behavior');

export const BEHAVIOR_OPERATORS: FlockOperatorDescriptor[] = [
  {
    id: 'flock.rules',
    version: 1,
    label: 'Flock Rules',
    category: 'behavior',
    description: 'Cohesion, separation and alignment against nearby particles.',
    phase: 'step',
    inputs: [selectionInput, port('weight', 'Weight', 'scalar', { drivesParam: 'weight' })],
    outputs: behaviorOutput,
    params: [
      numberParam('cohesion', 'Cohesion', 1, 'behavior', { min: 0, max: 10, step: 0.01 }),
      numberParam('separation', 'Separation', 1.6, 'behavior', { min: 0, max: 10, step: 0.01 }),
      numberParam('alignment', 'Alignment', 1.2, 'behavior', { min: 0, max: 10, step: 0.01 }),
      numberParam('neighborRadius', 'Neighborhood Radius', 12, 'behavior', { min: 0.1 }),
      numberParam('separationRadius', 'Separation Radius', 4, 'behavior', { min: 0.01 }),
      numberParam('fov', 'Field of View', 300, 'behavior', { min: 1, max: 360, unit: 'deg', advanced: true }),
      enumParam('groupMode', 'Group Interaction', 'all', ['all', 'same', 'other'], 'behavior', { advanced: true }),
      numberParam('weight', 'Weight', 1, 'behavior', { min: 0, max: 10, step: 0.01 }),
    ],
    bypass: { kind: 'mute' },
    maxInstances: 2,
  },
  {
    id: 'flock.attractor',
    version: 1,
    label: 'Attractor',
    category: 'behavior',
    description: 'Pulls or pushes particles toward a point.',
    phase: 'step',
    inputs: [selectionInput, port('strength', 'Strength', 'scalar', { drivesParam: 'strength' })],
    outputs: behaviorOutput,
    params: [
      vecParam('position', 'Position', [0, 0, 0], 'behavior'),
      numberParam('strength', 'Strength', 20, 'behavior'),
      numberParam('radius', 'Radius', 150, 'behavior', { min: 0.1 }),
      falloff,
      enumParam('mode', 'Mode', 'attract', ['attract', 'repel'], 'behavior'),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.vortex',
    version: 1,
    label: 'Vortex',
    category: 'behavior',
    description: 'Swirls particles around an axis.',
    phase: 'step',
    inputs: [selectionInput, port('strength', 'Strength', 'scalar', { drivesParam: 'strength' })],
    outputs: behaviorOutput,
    params: [
      vecParam('center', 'Center', [0, 0, 0], 'behavior'),
      vecParam('axis', 'Axis', [0, 1, 0], 'behavior'),
      numberParam('strength', 'Strength', 30, 'behavior'),
      numberParam('radius', 'Radius', 120, 'behavior', { min: 0.1 }),
      numberParam('inwardPull', 'Inward Pull', 0.3, 'behavior', { min: -5, max: 5, step: 0.01 }),
      falloff,
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.turbulence',
    version: 1,
    label: 'Turbulence',
    category: 'behavior',
    description: 'Smooth deterministic noise force evolving over source time.',
    phase: 'step',
    inputs: [selectionInput, port('strength', 'Strength', 'scalar', { drivesParam: 'strength' })],
    outputs: behaviorOutput,
    params: [
      numberParam('strength', 'Strength', 25, 'behavior', { min: 0 }),
      numberParam('frequency', 'Frequency', 0.02, 'behavior', { min: 0, step: 0.001 }),
      numberParam('evolution', 'Evolution', 0.3, 'behavior', { min: 0 }),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.drag',
    version: 1,
    label: 'Drag',
    category: 'behavior',
    description: 'Damps velocity.',
    phase: 'step',
    inputs: [selectionInput],
    outputs: behaviorOutput,
    params: [numberParam('amount', 'Amount', 0.4, 'behavior', { min: 0, max: 20, step: 0.01 })],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.wind',
    version: 1,
    label: 'Wind',
    category: 'behavior',
    description: 'Directional force with optional gusts.',
    phase: 'step',
    inputs: [selectionInput, port('strength', 'Strength', 'scalar', { drivesParam: 'strength' })],
    outputs: behaviorOutput,
    params: [
      vecParam('direction', 'Direction', [1, 0, 0], 'behavior'),
      numberParam('strength', 'Strength', 10, 'behavior'),
      numberParam('gust', 'Gust', 0.3, 'behavior', { min: 0, max: 1, step: 0.01 }),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.cruise',
    version: 1,
    label: 'Cruise Speed',
    category: 'behavior',
    description: 'Keeps particles near a preferred speed.',
    phase: 'step',
    inputs: [selectionInput],
    outputs: behaviorOutput,
    params: [
      numberParam('speed', 'Speed', 25, 'behavior', { min: 0 }),
      numberParam('strength', 'Strength', 2, 'behavior', { min: 0, step: 0.01 }),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.cluster',
    version: 1,
    label: 'Cluster Anchors',
    category: 'behavior',
    description: 'Deterministic wandering anchors that gather sub-clusters inside the swarm.',
    phase: 'step',
    inputs: [selectionInput, port('strength', 'Strength', 'scalar', { drivesParam: 'strength' })],
    outputs: behaviorOutput,
    params: [
      integerParam('clusters', 'Clusters', 6, 'behavior', { min: 1, max: 64 }),
      enumParam('assign', 'Assignment', 'identity', ['identity', 'group'], 'behavior'),
      vecParam('center', 'Center', [0, 0, 0], 'behavior'),
      numberParam('spread', 'Spread', 70, 'behavior', { min: 0 }),
      numberParam('wander', 'Wander Speed', 0.15, 'behavior', { min: 0 }),
      numberParam('strength', 'Strength', 8, 'behavior'),
      numberParam('radius', 'Pull Radius', 60, 'behavior', { min: 0.1 }),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.compose',
    version: 1,
    label: 'Compose Behavior',
    category: 'behavior',
    description: 'Sums behaviors in connection order.',
    phase: 'step',
    inputs: [port('behavior', 'Behavior', 'behavior', { required: true, repeated: true })],
    outputs: behaviorOutput,
    params: [],
    bypass: { kind: 'none' },
  },
];

export const GUIDANCE_OPERATORS: FlockOperatorDescriptor[] = [
  {
    id: 'flock.path',
    version: 1,
    label: 'Path',
    category: 'guidance',
    description: 'An analytic or polyline guide curve.',
    phase: 'step',
    inputs: [],
    outputs: [port('path', 'Path', 'path')],
    params: [
      enumParam('shape', 'Shape', 'circle', ['circle', 'figure8', 'helix', 'line', 'polyline'], 'behavior'),
      vecParam('center', 'Center', [0, 0, 0], 'behavior'),
      numberParam('radius', 'Radius', 90, 'behavior', { min: 0 }),
      numberParam('height', 'Height', 40, 'behavior'),
      numberParam('turns', 'Turns', 2, 'behavior', { min: 0.1, max: 20 }),
      vecParam('rotation', 'Rotation', [0, 0, 0], 'behavior', { unit: 'deg' }),
      vecParam('p0', 'Point 1', [-120, 0, 0], 'behavior', { advanced: true }),
      vecParam('p1', 'Point 2', [-40, 40, 30], 'behavior', { advanced: true }),
      vecParam('p2', 'Point 3', [40, -30, -30], 'behavior', { advanced: true }),
      vecParam('p3', 'Point 4', [120, 0, 0], 'behavior', { advanced: true }),
    ],
    bypass: { kind: 'none' },
    maxInstances: 4,
  },
  {
    id: 'flock.follow-path',
    version: 1,
    label: 'Follow Path',
    category: 'guidance',
    description: 'Steers particles along a path and into its tube.',
    phase: 'step',
    inputs: [
      port('path', 'Path', 'path', { required: true }),
      selectionInput,
      port('strength', 'Strength', 'scalar', { drivesParam: 'strength' }),
    ],
    outputs: behaviorOutput,
    params: [
      numberParam('strength', 'Strength', 25, 'behavior'),
      numberParam('tubeRadius', 'Tube Radius', 18, 'behavior', { min: 0 }),
      numberParam('lookahead', 'Lookahead', 0.04, 'behavior', { min: 0, max: 0.5, step: 0.005 }),
      enumParam('direction', 'Direction', 'forward', ['forward', 'backward'], 'behavior'),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.obstacle',
    version: 1,
    label: 'Obstacle',
    category: 'guidance',
    description: 'Analytic box / sphere / capsule / plane that particles avoid and cannot enter.',
    phase: 'step',
    inputs: [],
    outputs: [port('obstacle', 'Obstacle', 'obstacle')],
    params: [
      enumParam('shape', 'Shape', 'sphere', ['sphere', 'box', 'capsule', 'plane'], 'behavior'),
      vecParam('center', 'Center', [0, 0, 0], 'behavior'),
      vecParam('size', 'Size', [25, 25, 25], 'behavior', { min: 0 }),
      vecParam('rotation', 'Rotation', [0, 0, 0], 'behavior', { unit: 'deg' }),
      numberParam('avoidDistance', 'Avoid Distance', 15, 'behavior', { min: 0 }),
      numberParam('strength', 'Strength', 60, 'behavior', { min: 0 }),
    ],
    bypass: { kind: 'mute' },
    maxInstances: 16,
  },
  {
    id: 'flock.boundary',
    version: 1,
    label: 'Boundary',
    category: 'guidance',
    description: 'Wrap, contain, reflect or kill particles at a box or sphere boundary.',
    phase: 'step',
    inputs: [],
    outputs: [port('boundary', 'Boundary', 'boundary')],
    params: [
      enumParam('shape', 'Shape', 'sphere', ['sphere', 'box'], 'behavior'),
      vecParam('center', 'Center', [0, 0, 0], 'behavior'),
      vecParam('size', 'Size', [160, 160, 160], 'behavior', { min: 1 }),
      enumParam('mode', 'Mode', 'contain', ['contain', 'wrap', 'reflect', 'kill'], 'behavior'),
      numberParam('softness', 'Softness', 30, 'behavior', { min: 0 }),
      numberParam('strength', 'Strength', 40, 'behavior', { min: 0 }),
    ],
    bypass: { kind: 'none' },
    maxInstances: 1,
  },
];
