import type { FlockOperatorDescriptor } from './flockOperatorTypes';
import {
  assetParam,
  colorParam,
  enumParam,
  integerParam,
  numberParam,
  port,
} from './flockParamBuilders';

const sceneOutput = [port('scene', 'Scene', 'scene')];
const particlesInput = port('particles', 'Particles', 'particles', { required: true });
const selectionInput = port('selection', 'Selection', 'selection');
const paletteInput = port('palette', 'Palette', 'palette');
const blend = (value: string) => enumParam('blend', 'Blend', value, ['additive', 'alpha', 'opaque'], 'appearance');
const colorMode = (value: string, extra: string[] = []) => enumParam(
  'colorMode',
  'Color Mode',
  value,
  ['constant', 'palette', 'speed', 'age', 'group', 'density', ...extra],
  'appearance',
);

export const FLOCK_MAX_TRAILS = 65_536;
export const FLOCK_MAX_TRAIL_SAMPLES = 64;
export const FLOCK_MAX_LINKS = 262_144;

export const RENDER_OPERATORS: FlockOperatorDescriptor[] = [
  {
    id: 'flock.render-points',
    version: 1,
    label: 'Points',
    category: 'render',
    description: 'Camera-facing dots, soft sprites or shapes per particle.',
    phase: 'render',
    inputs: [particlesInput, selectionInput, paletteInput],
    outputs: sceneOutput,
    params: [
      enumParam('shape', 'Shape', 'soft', ['dot', 'soft', 'square', 'ring', 'star'], 'appearance'),
      numberParam('size', 'Size', 4, 'appearance', { min: 0, max: 200, step: 0.1 }),
      enumParam('sizeMode', 'Size Mode', 'screen', ['screen', 'world'], 'appearance'),
      numberParam('sizeVariance', 'Size Variance', 0.35, 'appearance', { min: 0, max: 1, step: 0.01 }),
      colorParam('color', 'Color', '#9fd8ff'),
      colorMode('constant'),
      numberParam('opacity', 'Opacity', 0.85, 'appearance', { min: 0, max: 1, step: 0.01 }),
      numberParam('distanceFade', 'Distance Fade', 0.5, 'appearance', { min: 0, max: 1, step: 0.01, advanced: true }),
      blend('additive'),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.render-instances',
    version: 1,
    label: 'Instances',
    category: 'render',
    description: 'Instanced low-poly bodies oriented along velocity, with phase-shifted swimming deformation.',
    phase: 'render',
    inputs: [particlesInput, selectionInput, paletteInput],
    outputs: sceneOutput,
    params: [
      enumParam('mesh', 'Mesh', 'krill', ['krill', 'fish', 'arrow', 'tetra', 'cube', 'sphere', 'model'], 'appearance'),
      assetParam('model', 'Model Asset', 'model', 'appearance', { advanced: true }),
      enumParam('forwardAxis', 'Forward Axis', '+z', ['+z', '-z', '+x', '-x', '+y', '-y'], 'appearance', { advanced: true }),
      numberParam('size', 'Size', 2.2, 'appearance', { min: 0, step: 0.05 }),
      numberParam('sizeVariance', 'Size Variance', 0.3, 'appearance', { min: 0, max: 1, step: 0.01 }),
      colorParam('color', 'Color', '#ff9b7a'),
      colorMode('constant'),
      numberParam('swimAmplitude', 'Swim Amplitude', 0.25, 'appearance', { min: 0, max: 2, step: 0.01 }),
      numberParam('swimFrequency', 'Swim Frequency', 3, 'appearance', { min: 0, max: 30, step: 0.1, unit: 'Hz' }),
      numberParam('phaseVariation', 'Phase Variation', 1, 'appearance', { min: 0, max: 1, step: 0.01 }),
      enumParam('shading', 'Shading', 'lit', ['lit', 'flat', 'emissive'], 'appearance'),
      numberParam('opacity', 'Opacity', 1, 'appearance', { min: 0, max: 1, step: 0.01 }),
      blend('opaque'),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.render-links',
    version: 1,
    label: 'Neighbor Links',
    category: 'render',
    description: 'Bounded, deduplicated links between nearby particle identities with distance fading.',
    phase: 'derived',
    inputs: [particlesInput, selectionInput, paletteInput],
    outputs: sceneOutput,
    params: [
      numberParam('radius', 'Link Distance', 10, 'derived', { min: 0.1 }),
      integerParam('perParticle', 'Links Per Particle', 2, 'derived', { min: 1, max: 8 }),
      numberParam('sampleFraction', 'Sample Fraction', 0.3, 'derived', { min: 0, max: 1, step: 0.01 }),
      integerParam('maxLinks', 'Max Links', 20_000, 'derived', { min: 1, max: 262_144, advanced: true }),
      numberParam('fadeBand', 'Fade Band', 0.4, 'appearance', { min: 0, max: 1, step: 0.01 }),
      numberParam('width', 'Width', 1, 'appearance', { min: 0.1, max: 20, step: 0.1 }),
      colorParam('color', 'Color', '#8fe3ff'),
      enumParam('colorMode', 'Color Mode', 'constant', ['constant', 'distance', 'palette', 'group'], 'appearance'),
      numberParam('opacity', 'Opacity', 0.45, 'appearance', { min: 0, max: 1, step: 0.01 }),
      blend('additive'),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.trails',
    version: 1,
    label: 'Trails',
    category: 'render',
    description: 'Records a stable subset of identities into bounded history rings.',
    phase: 'step',
    inputs: [particlesInput],
    outputs: [port('curves', 'Curves', 'curves')],
    params: [
      numberParam('sampleFraction', 'Sample Fraction', 0.08, 'topology', { min: 0, max: 1, step: 0.005 }),
      integerParam('maxTrails', 'Max Trails', 2000, 'topology', { min: 1, max: FLOCK_MAX_TRAILS }),
      integerParam('samples', 'Length (Samples)', 24, 'topology', { min: 2, max: FLOCK_MAX_TRAIL_SAMPLES }),
      integerParam('interval', 'Sample Interval (Steps)', 3, 'topology', { min: 1, max: 60 }),
      integerParam('salt', 'Salt', 7, 'topology', { min: 0, max: 9999, advanced: true }),
    ],
    bypass: { kind: 'none' },
    maxInstances: 4,
  },
  {
    id: 'flock.render-curves',
    version: 1,
    label: 'Curves',
    category: 'render',
    description: 'Smooth tapered ribbons along recorded trails.',
    phase: 'render',
    inputs: [port('curves', 'Curves', 'curves', { required: true }), selectionInput, paletteInput],
    outputs: sceneOutput,
    params: [
      numberParam('width', 'Width', 1.4, 'appearance', { min: 0.1, max: 40, step: 0.1 }),
      enumParam('widthMode', 'Width Mode', 'screen', ['screen', 'world'], 'appearance'),
      numberParam('taper', 'Tail Width', 0.1, 'appearance', { min: 0, max: 1, step: 0.01 }),
      numberParam('fadeTail', 'Tail Fade', 1, 'appearance', { min: 0, max: 1, step: 0.01 }),
      enumParam('smoothing', 'Smoothing', 'catmull', ['none', 'catmull'], 'appearance'),
      integerParam('subdivisions', 'Subdivisions', 3, 'appearance', { min: 1, max: 6 }),
      colorParam('color', 'Color', '#c9a6ff'),
      enumParam('colorMode', 'Color Mode', 'constant', ['constant', 'palette', 'group', 'along'], 'appearance'),
      colorParam('tailColor', 'Tail Color', '#3b1a7a', { advanced: true }),
      numberParam('opacity', 'Opacity', 0.8, 'appearance', { min: 0, max: 1, step: 0.01 }),
      blend('additive'),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.render-glyphs',
    version: 1,
    label: 'Endpoint Glyphs',
    category: 'render',
    description: 'Sparse technical markers at particles or trail endpoints.',
    phase: 'render',
    inputs: [
      port('particles', 'Particles', 'particles'),
      port('curves', 'Curves', 'curves'),
      paletteInput,
    ],
    outputs: sceneOutput,
    params: [
      enumParam('anchor', 'Anchor', 'trail-head', ['particles', 'trail-head', 'trail-tail'], 'appearance'),
      enumParam('glyph', 'Glyph', 'square', ['dot', 'ring', 'square', 'cube', 'cross', 'diamond'], 'appearance'),
      numberParam('size', 'Size', 6, 'appearance', { min: 0.1, max: 200, step: 0.1 }),
      enumParam('sizeMode', 'Size Mode', 'screen', ['screen', 'world'], 'appearance'),
      numberParam('sampleFraction', 'Sample Fraction', 0.15, 'appearance', { min: 0, max: 1, step: 0.01 }),
      enumParam('orientation', 'Orientation', 'camera', ['camera', 'world'], 'appearance'),
      numberParam('lineWidth', 'Line Width', 1, 'appearance', { min: 0.1, max: 10, step: 0.1 }),
      colorParam('color', 'Color', '#ffffff'),
      enumParam('colorMode', 'Color Mode', 'constant', ['constant', 'palette', 'group'], 'appearance'),
      numberParam('opacity', 'Opacity', 0.9, 'appearance', { min: 0, max: 1, step: 0.01 }),
      blend('additive'),
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.render-vectors',
    version: 1,
    label: 'Velocity Vectors',
    category: 'render',
    description: 'Heading or velocity strokes on a sampled subset.',
    phase: 'render',
    inputs: [particlesInput, selectionInput, paletteInput],
    outputs: sceneOutput,
    params: [
      enumParam('mode', 'Mode', 'velocity', ['velocity', 'heading'], 'appearance'),
      numberParam('scale', 'Scale', 0.25, 'appearance', { min: 0, step: 0.01 }),
      numberParam('sampleFraction', 'Sample Fraction', 0.1, 'appearance', { min: 0, max: 1, step: 0.01 }),
      numberParam('width', 'Width', 1, 'appearance', { min: 0.1, max: 10, step: 0.1 }),
      colorParam('color', 'Color', '#ffe28a'),
      colorMode('speed'),
      numberParam('opacity', 'Opacity', 0.7, 'appearance', { min: 0, max: 1, step: 0.01 }),
      blend('additive'),
    ],
    bypass: { kind: 'mute' },
  },
];
