import type { FlockOperatorDescriptor } from './flockOperatorTypes';
import {
  assetParam,
  boolParam,
  colorParam,
  enumParam,
  integerParam,
  numberParam,
  port,
  vecParam,
} from './flockParamBuilders';

const selectionOutput = [port('selection', 'Selection', 'selection')];
const invert = boolParam('invert', 'Invert', false, 'behavior');

export const SELECTION_OPERATORS: FlockOperatorDescriptor[] = [
  {
    id: 'flock.select-group',
    version: 1,
    label: 'Select Group',
    category: 'selection',
    description: 'Selects particles spawned into one emitter group.',
    phase: 'step',
    inputs: [],
    outputs: selectionOutput,
    params: [integerParam('group', 'Group', 0, 'behavior', { min: 0, max: 7 }), invert],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.select-fraction',
    version: 1,
    label: 'Select ID Fraction',
    category: 'selection',
    description: 'Selects a stable fraction of particle identities.',
    phase: 'step',
    inputs: [],
    outputs: selectionOutput,
    params: [
      numberParam('fraction', 'Fraction', 0.25, 'behavior', { min: 0, max: 1, step: 0.01 }),
      integerParam('salt', 'Salt', 1, 'behavior', { min: 0, max: 9999 }),
      invert,
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.select-region',
    version: 1,
    label: 'Select Region',
    category: 'selection',
    description: 'Selects particles inside a sphere or box.',
    phase: 'step',
    inputs: [],
    outputs: selectionOutput,
    params: [
      enumParam('shape', 'Shape', 'sphere', ['sphere', 'box'], 'behavior'),
      vecParam('center', 'Center', [0, 0, 0], 'behavior'),
      vecParam('size', 'Size', [60, 60, 60], 'behavior', { min: 0 }),
      invert,
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.select-speed',
    version: 1,
    label: 'Select Speed',
    category: 'selection',
    description: 'Selects particles whose speed is inside a range.',
    phase: 'step',
    inputs: [],
    outputs: selectionOutput,
    params: [
      numberParam('min', 'Min', 0, 'behavior', { min: 0 }),
      numberParam('max', 'Max', 100, 'behavior', { min: 0 }),
      invert,
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.select-age',
    version: 1,
    label: 'Select Age',
    category: 'selection',
    description: 'Selects particles by age in seconds.',
    phase: 'step',
    inputs: [],
    outputs: selectionOutput,
    params: [
      numberParam('min', 'Min', 0, 'behavior', { min: 0, unit: 's' }),
      numberParam('max', 'Max', 5, 'behavior', { min: 0, unit: 's' }),
      invert,
    ],
    bypass: { kind: 'mute' },
  },
  {
    id: 'flock.select-combine',
    version: 1,
    label: 'Combine Selections',
    category: 'selection',
    description: 'Combines two selections with and / or / xor.',
    phase: 'step',
    inputs: [port('a', 'A', 'selection', { required: true }), port('b', 'B', 'selection', { required: true })],
    outputs: selectionOutput,
    params: [enumParam('mode', 'Mode', 'and', ['and', 'or', 'xor'], 'behavior'), invert],
    bypass: { kind: 'passthrough', input: 'a', output: 'selection' },
  },
];

const scalarOutput = [port('value', 'Value', 'scalar')];

export const VALUE_OPERATORS: FlockOperatorDescriptor[] = [
  {
    id: 'flock.value',
    version: 1,
    label: 'Value',
    category: 'values',
    description: 'An animatable scalar for driving several parameters.',
    phase: 'value',
    inputs: [],
    outputs: scalarOutput,
    params: [numberParam('value', 'Value', 1, 'behavior')],
    bypass: { kind: 'none' },
  },
  {
    id: 'flock.math',
    version: 1,
    label: 'Math',
    category: 'values',
    description: 'Combines two scalars.',
    phase: 'value',
    inputs: [
      port('a', 'A', 'scalar', { drivesParam: 'a' }),
      port('b', 'B', 'scalar', { drivesParam: 'b' }),
    ],
    outputs: scalarOutput,
    params: [
      enumParam('op', 'Operation', 'multiply', ['add', 'subtract', 'multiply', 'divide', 'min', 'max', 'power', 'abs', 'sin'], 'behavior'),
      numberParam('a', 'A', 1, 'behavior'),
      numberParam('b', 'B', 1, 'behavior'),
    ],
    bypass: { kind: 'passthrough', input: 'a', output: 'value' },
  },
  {
    id: 'flock.remap',
    version: 1,
    label: 'Remap',
    category: 'values',
    description: 'Maps a scalar range to another range with an optional ease.',
    phase: 'value',
    inputs: [port('input', 'In', 'scalar', { drivesParam: 'input' })],
    outputs: scalarOutput,
    params: [
      numberParam('input', 'In', 0, 'behavior'),
      numberParam('inMin', 'In Min', 0, 'behavior'),
      numberParam('inMax', 'In Max', 1, 'behavior'),
      numberParam('outMin', 'Out Min', 0, 'behavior'),
      numberParam('outMax', 'Out Max', 1, 'behavior'),
      enumParam('curve', 'Curve', 'linear', ['linear', 'smooth', 'ease-in', 'ease-out'], 'behavior'),
      boolParam('clamp', 'Clamp', true, 'behavior'),
    ],
    bypass: { kind: 'passthrough', input: 'input', output: 'value' },
  },
  {
    id: 'flock.oscillator',
    version: 1,
    label: 'Oscillator',
    category: 'values',
    description: 'A deterministic ramp / LFO over source time.',
    phase: 'value',
    inputs: [],
    outputs: scalarOutput,
    params: [
      enumParam('wave', 'Wave', 'sine', ['sine', 'triangle', 'saw', 'square', 'noise'], 'behavior'),
      numberParam('frequency', 'Frequency', 0.25, 'behavior', { min: 0, unit: 'Hz' }),
      numberParam('amplitude', 'Amplitude', 1, 'behavior'),
      numberParam('offset', 'Offset', 0, 'behavior'),
      numberParam('phase', 'Phase', 0, 'behavior', { min: 0, max: 1, step: 0.01 }),
    ],
    bypass: { kind: 'none' },
  },
  {
    id: 'flock.time',
    version: 1,
    label: 'Source Time',
    category: 'values',
    description: 'The simulation source time in seconds.',
    phase: 'value',
    inputs: [],
    outputs: scalarOutput,
    params: [
      numberParam('scale', 'Scale', 1, 'behavior'),
      numberParam('offset', 'Offset', 0, 'behavior'),
    ],
    bypass: { kind: 'none' },
  },
  {
    id: 'flock.audio',
    version: 1,
    label: 'Audio Level',
    category: 'values',
    description: 'Reads an existing audio analysis (loudness) at source time. Missing analysis reports unavailable.',
    phase: 'value',
    inputs: [],
    outputs: scalarOutput,
    params: [
      assetParam('clipId', 'Audio Clip', 'audio', 'behavior'),
      numberParam('gain', 'Gain', 1, 'behavior', { min: 0 }),
      numberParam('offset', 'Time Offset', 0, 'behavior', { unit: 's' }),
      numberParam('floor', 'Floor', 0, 'behavior', { min: 0, max: 1, step: 0.01 }),
      numberParam('smoothing', 'Smoothing', 0.1, 'behavior', { min: 0, max: 2, unit: 's' }),
    ],
    bypass: { kind: 'none' },
  },
  {
    id: 'flock.palette',
    version: 1,
    label: 'Palette',
    category: 'values',
    description: 'Four colors mapped by group, identity, position, speed or age.',
    phase: 'render',
    inputs: [],
    outputs: [port('palette', 'Palette', 'palette')],
    params: [
      colorParam('color1', 'Color 1', '#6b2bd9'),
      colorParam('color2', 'Color 2', '#b86bff'),
      colorParam('color3', 'Color 3', '#ffd6ff'),
      colorParam('color4', 'Color 4', '#3a0f7a'),
      enumParam('mode', 'Mapping', 'position', ['group', 'identity', 'position', 'speed', 'age'], 'appearance'),
      numberParam('frequency', 'Frequency', 0.004, 'appearance', { min: 0, step: 0.0005 }),
      numberParam('range', 'Range', 60, 'appearance', { min: 0.001 }),
    ],
    bypass: { kind: 'none' },
  },
];

export const OUTPUT_OPERATORS: FlockOperatorDescriptor[] = [
  {
    id: 'flock.output',
    version: 1,
    label: 'Scene Output',
    category: 'output',
    description: 'Collects render branches into the shared 3D scene.',
    phase: 'output',
    inputs: [port('scene', 'Scene', 'scene', { required: true, repeated: true })],
    outputs: [],
    params: [],
    bypass: { kind: 'none' },
    maxInstances: 1,
  },
  {
    id: 'flock.group',
    version: 1,
    label: 'Group',
    category: 'groups',
    description: 'A reusable node group. Ports come from the group definition.',
    phase: 'structure',
    inputs: [],
    outputs: [],
    params: [],
    bypass: { kind: 'mute' },
  },
];
