// Voxel Relief - raymarched brightness-driven block extrusion.

import shader from './shader.wgsl?raw';
import type { EffectDefinition } from '../../types';

export const voxelRelief: EffectDefinition = {
  id: 'voxel-relief',
  name: 'Voxel Relief',
  category: 'stylize',

  shader,
  entryPoint: 'voxelReliefFragment',
  uniformSize: 112,
  usesFeedback: true,

  cameraInteraction: {
    yawParam: 'yaw',
    tiltParam: 'tilt',
    distanceParam: 'distance',
    centerXParam: 'centerX',
    centerYParam: 'centerY',
    yawWrap: true,
    tiltWrap: true,
  },

  params: {
    columns: {
      type: 'number',
      label: 'Columns',
      default: 107.4,
      min: 12,
      max: 180,
      step: 1,
      animatable: true,
      group: 'relief',
    },
    height: {
      type: 'number',
      label: 'Height',
      default: 1.2,
      min: 0,
      max: 1.2,
      step: 0.01,
      animatable: true,
      group: 'relief',
    },
    baseHeight: {
      type: 'number',
      label: 'Base',
      default: 0.015,
      min: 0,
      max: 0.2,
      step: 0.005,
      animatable: true,
      group: 'relief',
    },
    gap: {
      type: 'number',
      label: 'Gap',
      default: 0.06,
      min: 0,
      max: 0.36,
      step: 0.01,
      animatable: true,
      group: 'relief',
    },
    limitToVideo: {
      type: 'boolean',
      label: 'Limit to Video',
      default: true,
      animatable: false,
      group: 'relief',
    },
    tilt: {
      type: 'number',
      label: 'Tilt',
      default: 87,
      min: -180,
      max: 180,
      step: 1,
      animatable: true,
      group: 'camera',
    },
    yaw: {
      type: 'number',
      label: 'Yaw',
      default: 0,
      min: -180,
      max: 180,
      step: 1,
      animatable: true,
      group: 'camera',
    },
    perspective: {
      type: 'number',
      label: 'FOV',
      default: 0.22,
      min: 0.15,
      max: 1.6,
      step: 0.01,
      animatable: true,
      group: 'camera',
    },
    distance: {
      type: 'number',
      label: 'Distance',
      default: 1,
      min: 0.2,
      max: 6,
      step: 0.01,
      animatable: true,
      group: 'camera',
    },
    centerX: {
      type: 'number',
      label: 'Center X',
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.005,
      animatable: true,
      group: 'camera',
    },
    centerY: {
      type: 'number',
      label: 'Center Y',
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.005,
      animatable: true,
      group: 'camera',
    },
    roll: {
      type: 'number',
      label: 'Roll',
      default: 0,
      min: -180,
      max: 180,
      step: 1,
      animatable: true,
      group: 'camera',
    },
    heightContrast: {
      type: 'number',
      label: 'Height Contrast',
      default: 3,
      min: 0.2,
      max: 3,
      step: 0.01,
      animatable: true,
      group: 'relief',
    },
    ambient: {
      type: 'number',
      label: 'Ambient',
      default: 0.58,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
      group: 'light',
    },
    lightStrength: {
      type: 'number',
      label: 'Light',
      default: 0.48,
      min: 0,
      max: 2,
      step: 0.01,
      animatable: true,
      group: 'light',
    },
    colorMix: {
      type: 'number',
      label: 'Color',
      default: 0.95,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
      group: 'look',
    },
    temporalBlend: {
      type: 'number',
      label: 'Smoothing',
      default: 0.08,
      min: 0,
      max: 0.9,
      step: 0.01,
      animatable: true,
      group: 'look',
    },
    lightAngle: {
      type: 'number',
      label: 'Light Angle',
      default: 310,
      min: 0,
      max: 360,
      step: 1,
      animatable: true,
      group: 'light',
    },
    lightElevation: {
      type: 'number',
      label: 'Light Elevation',
      default: 45,
      min: 5,
      max: 85,
      step: 1,
      animatable: true,
      group: 'light',
    },
    lightFollow: {
      type: 'boolean',
      label: 'Light Follows Camera',
      default: false,
      animatable: false,
      group: 'light',
    },
    floorBrightness: {
      type: 'number',
      label: 'Gaps',
      default: 0.1,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
      group: 'look',
    },
    edgeDarkness: {
      type: 'number',
      label: 'Edges',
      default: 0.68,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
      group: 'look',
    },
    maxSteps: {
      type: 'number',
      label: 'Ray Steps',
      default: 72,
      min: 24,
      max: 144,
      step: 1,
      animatable: false,
      quality: true,
    },
    reset: {
      type: 'boolean',
      label: 'Reset Smoothing',
      default: false,
      animatable: false,
      group: 'look',
    },
  },

  packUniforms: (params, width, height) => {
    const reset = params.reset === true ? 1 : 0;

    return new Float32Array([
      Number(params.columns ?? 107.4),
      Number(params.height ?? 1.2),
      Number(params.baseHeight ?? 0.015),
      Number(params.gap ?? 0.06),
      Number(params.tilt ?? 87),
      Number(params.yaw ?? 0),
      Number(params.perspective ?? 0.22),
      Number(params.heightContrast ?? 3),
      Number(params.ambient ?? 0.58),
      Number(params.lightStrength ?? 0.48),
      Number(params.temporalBlend ?? 0.08),
      Number(params.colorMix ?? 0.95),
      width,
      height,
      Number(params.maxSteps ?? 72),
      reset,
      Number(params.lightAngle ?? 310),
      Number(params.lightElevation ?? 45),
      Number(params.floorBrightness ?? 0.1),
      Number(params.edgeDarkness ?? 0.68),
      Number(params.distance ?? 1),
      Number(params.centerX ?? 0.5),
      Number(params.centerY ?? 0.5),
      Number(params.roll ?? 0),
      params.lightFollow === true ? 1 : 0,
      params.limitToVideo !== false ? 1 : 0,
      0,
      0,
    ]);
  },
};
