import type { EffectParam } from '../../types';
import { FEEDBACK_PARAMETERS } from '../../_shared/feedbackParameters';

/** One schema for the effect form, reusable operator bindings and rendering. */
export const VOXEL_RELIEF_PARAMS: Record<string, EffectParam> = {
    ...FEEDBACK_PARAMETERS,
    columns: {
      type: 'number',
      label: 'Columns',
      default: 107.4,
      min: 12,
      max: 180,
      step: 1,
      animatable: true,
      group: 'relief',
    },
    height: {
      type: 'number',
      label: 'Height',
      default: 1.2,
      min: 0,
      max: 1.2,
      step: 0.01,
      animatable: true,
      group: 'relief',
    },
    baseHeight: {
      type: 'number',
      label: 'Base',
      default: 0.015,
      min: 0,
      max: 0.2,
      step: 0.005,
      animatable: true,
      group: 'relief',
    },
    gap: {
      type: 'number',
      label: 'Gap',
      default: 0.06,
      min: 0,
      max: 0.36,
      step: 0.01,
      animatable: true,
      group: 'relief',
    },
    limitToVideo: {
      type: 'boolean',
      label: 'Limit to Video',
      default: true,
      animatable: false,
      group: 'relief',
    },
    tilt: {
      type: 'number',
      label: 'Tilt',
      default: 87,
      min: -180,
      max: 180,
      step: 1,
      animatable: true,
      group: 'camera',
    },
    yaw: {
      type: 'number',
      label: 'Yaw',
      default: 0,
      min: -180,
      max: 180,
      step: 1,
      animatable: true,
      group: 'camera',
    },
    perspective: {
      type: 'number',
      label: 'FOV',
      default: 0.22,
      min: 0.15,
      max: 1.6,
      step: 0.01,
      animatable: true,
      group: 'camera',
    },
    distance: {
      type: 'number',
      label: 'Distance',
      default: 1,
      min: 0.2,
      max: 6,
      step: 0.01,
      animatable: true,
      group: 'camera',
    },
    centerX: {
      type: 'number',
      label: 'Center X',
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.005,
      animatable: true,
      group: 'camera',
    },
    centerY: {
      type: 'number',
      label: 'Center Y',
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.005,
      animatable: true,
      group: 'camera',
    },
    roll: {
      type: 'number',
      label: 'Roll',
      default: 0,
      min: -180,
      max: 180,
      step: 1,
      animatable: true,
      group: 'camera',
    },
    heightContrast: {
      type: 'number',
      label: 'Height Contrast',
      default: 3,
      min: 0.2,
      max: 3,
      step: 0.01,
      animatable: true,
      group: 'relief',
    },
    ambient: {
      type: 'number',
      label: 'Ambient',
      default: 0.58,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
      group: 'light',
    },
    lightStrength: {
      type: 'number',
      label: 'Light',
      default: 0.48,
      min: 0,
      max: 2,
      step: 0.01,
      animatable: true,
      group: 'light',
    },
    colorMix: {
      type: 'number',
      label: 'Color',
      default: 0.95,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
      group: 'look',
    },
    temporalBlend: {
      type: 'number',
      label: 'Smoothing',
      default: 0.08,
      min: 0,
      max: 0.9,
      step: 0.01,
      animatable: true,
      group: 'look',
    },
    lightAngle: {
      type: 'number',
      label: 'Light Angle',
      default: 310,
      min: 0,
      max: 360,
      step: 1,
      animatable: true,
      group: 'light',
    },
    lightElevation: {
      type: 'number',
      label: 'Light Elevation',
      default: 45,
      min: 5,
      max: 85,
      step: 1,
      animatable: true,
      group: 'light',
    },
    lightFollow: {
      type: 'boolean',
      label: 'Light Follows Camera',
      default: false,
      animatable: false,
      group: 'light',
    },
    floorBrightness: {
      type: 'number',
      label: 'Gaps',
      default: 0.1,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
      group: 'look',
    },
    edgeDarkness: {
      type: 'number',
      label: 'Edges',
      default: 0.68,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
      group: 'look',
    },
    maxSteps: {
      type: 'number',
      label: 'Ray Steps',
      default: 72,
      min: 24,
      max: 144,
      step: 1,
      animatable: false,
      quality: true,
    },
    reset: {
      type: 'boolean',
      label: 'Reset Smoothing',
      default: false,
      animatable: false,
      group: 'look',
    },
  };
