/**
 * Catalog text for nodes and effects: a one-sentence description (d) and search
 * synonyms (t) per catalog ID (effect:, audio:, control:, color:, builtin: or an
 * operator ID). Written from the implementations; see docs/ongoing/Node-Taxonomy-Plan.md.
 */
const CATALOG_TEXT: Readonly<Record<string, { d?: string; t?: readonly string[] }>> = {
  "analog.display-resolve": { d: "Shows the decoded picture on a CRT with scanlines, phosphor mask, bloom, screen curvature and field flicker; Mix blends with the source.", t: ["crt", "scanlines", "phosphor", "bloom", "tv display"] },
  "analog.pal-decode": { d: "Decodes the PAL signal back into a color image with limited luma and chroma bandwidth and Y/C crosstalk; PAL Decoder picks the method.", t: ["pal decode", "composite", "dot crawl", "color bleed", "decoder"] },
  "analog.pal-encode": { d: "Encodes the image into a PAL composite TV signal; Chroma Level and PAL Phase Error shape how color is carried.", t: ["pal", "composite video", "encode", "analog tv"] },
  "analog.receiver-analyze": { d: "Measures each line's sync and color burst like a TV receiver for decoding; Sync Instability and Color Lock set how steady the picture is.", t: ["sync", "color burst", "receiver", "picture hold", "line timing"] },
  "analog.rf-channel": { d: "Simulates antenna reception: weak signal, RF snow, impulse noise, ghost echoes, co-channel interference and tuning drift.", t: ["rf", "antenna", "snow", "ghosting", "interference", "tv reception"] },
  "analog.vhs-transport": { d: "Passes the signal through a VHS tape: tracking errors, dropouts, time-base wobble, tape wear, chroma bleed and head-switching noise.", t: ["vhs", "tape", "tracking", "dropouts", "videotape"] },
  "audio:audio-channel-swap": { d: "Swaps the left and right channels.", t: ["swap left right", "reverse stereo", "channel flip"] },
  "audio:audio-compressor": { d: "Reduces the level of loud parts above Threshold by Ratio to even out dynamics; Attack, Release, Knee and Makeup Gain shape it.", t: ["dynamics", "leveling", "squash", "punch", "evening out"] },
  "audio:audio-de-click": { d: "Detects sudden single-sample spikes and replaces them with a smoothed value to remove clicks and pops; Threshold sets sensitivity.", t: ["click removal", "pop removal", "crackle", "repair", "vinyl"] },
  "audio:audio-de-esser": { d: "Compresses only frequencies above the split point (6.5 kHz by default) to tame harsh s and sh sounds; Threshold and Ratio set the strength.", t: ["sibilance", "harsh s", "vocal", "dynamics", "voice"] },
  "audio:audio-delay": { d: "Adds echoes of the sound after Delay milliseconds; Feedback sets how many repeats, Mix the echo level, Tone darkens them.", t: ["echo", "repeat", "slapback", "feedback delay"] },
  "audio:audio-eq": { d: "Ten-band graphic equalizer that boosts or cuts fixed bands from 31 Hz to 16 kHz.", t: ["graphic eq", "equalizer", "bass", "treble", "tone"] },
  "audio:audio-expander": { d: "Pushes quiet audio below Threshold even quieter by Ratio, up to Range, to increase dynamics and reduce low-level noise.", t: ["downward expander", "dynamics", "noise reduction", "gate"] },
  "audio:audio-high-pass": { d: "Removes low frequencies below the cutoff, such as rumble or wind noise; Q shapes the slope near the cutoff.", t: ["low cut", "hpf", "rumble filter", "bass cut"] },
  "audio:audio-hum-notch": { d: "Removes electrical mains hum at 50 or 60 Hz and its harmonics with narrow notch filters; Q sets notch width.", t: ["hum removal", "mains hum", "buzz", "notch filter", "ground loop"] },
  "audio:audio-limiter": { d: "Prevents peaks from exceeding the Ceiling so the audio never clips; Input Gain pushes the level into the limiter.", t: ["peak limiter", "clipping protection", "loudness", "brickwall", "ceiling"] },
  "audio:audio-low-pass": { d: "Removes high frequencies above the cutoff for a muffled or darker sound; Q shapes the slope near the cutoff.", t: ["high cut", "lpf", "muffle", "treble cut"] },
  "audio:audio-math": { d: "Processes audio samples with a custom node graph of math operations such as multiply, add, clamp, sine and mix.", t: ["audio nodes", "sample math", "waveshaping", "custom audio", "dsp graph"] },
  "audio:audio-mono-sum": { d: "Mixes all channels together and plays the same mono signal on every channel.", t: ["mono", "downmix", "collapse stereo", "sum to mono"] },
  "audio:audio-noise-gate": { d: "Mutes audio that falls below Threshold down to Floor, cutting noise in pauses; Attack and Release set how fast it opens and closes.", t: ["gate", "silence pauses", "noise cut", "dynamics", "mute"] },
  "audio:audio-noise-reduction": { d: "Lowers the level of quiet passages below Threshold to suppress background noise between sounds; Reduction sets how much.", t: ["denoise", "background noise", "hiss", "downward expander", "cleanup"] },
  "audio:audio-normalize": { d: "Adjusts the clip's overall gain to reach a target peak, RMS or LUFS loudness, with a true-peak ceiling and a maximum boost.", t: ["loudness", "lufs", "peak level", "level matching", "gain"] },
  "audio:audio-pan": { d: "Positions the sound between the left and right speakers; Pan runs from -1 (left) through 0 (center) to 1 (right).", t: ["balance", "stereo position", "left right", "panning"] },
  "audio:audio-parametric-eq": { d: "Boosts or cuts one adjustable frequency band; Frequency sets its center, Gain the amount, Q the width.", t: ["bell filter", "peaking eq", "equalizer", "tone", "frequency boost"] },
  "audio:audio-polarity-invert": { d: "Flips the waveform upside down on all, left or right channels, e.g. to fix phase cancellation between microphones.", t: ["phase invert", "phase flip", "polarity", "phase fix"] },
  "audio:audio-reverb": { d: "Adds room reverberation; Room Size and Decay set the space and tail length, Damping softens highs, Mix the wet level.", t: ["room", "hall", "ambience", "echo", "space"] },
  "audio:audio-saturation": { d: "Adds warm harmonic distortion by driving the signal; Drive sets intensity, Tone filters the highs, Mix blends with the dry sound.", t: ["distortion", "overdrive", "warmth", "tape saturation", "drive"] },
  "audio:audio-spectral-gate": { d: "Splits audio into low, mid and high bands and gates each separately when it drops below Threshold; the Hz settings set the band edges.", t: ["multiband gate", "noise gate", "denoise", "frequency gate", "cleanup"] },
  "audio:audio-stereo-split": { d: "Copies one chosen source channel to all channels, e.g. to use only the left microphone on both sides.", t: ["dual mono", "channel select", "left only", "right only", "use one channel"] },
  "audio:audio-volume": { d: "Scales the clip's loudness by a gain factor (1 = unchanged, 0 = silent), with sample-accurate automation.", t: ["gain", "level", "loudness", "fader", "amplify"] },
  "builtin:ai": { d: "Custom node whose image-processing code is generated by AI from a text prompt, with its own exposed, keyframable parameters.", t: ["ai node", "custom node", "generated code", "prompt", "script"] },
  "builtin:color": { d: "Runs the clip's color-correction graph (Corrector and Wheels nodes) on the image at its place in the effect stack.", t: ["color grade", "color correction", "grading", "color graph"] },
  "builtin:keyframes": { d: "Holds keyframe animation channels for chosen parameters and can link other parameters to follow the same curve.", t: ["animation", "keyframes", "curves", "automation", "link parameters"] },
  "builtin:mask": { d: "Applies the clip's active masks to cut out or reveal parts of the image.", t: ["masks", "cutout", "matte", "roto", "shape mask"] },
  "builtin:output": { d: "End of the clip's graph: the final signal used by the timeline, preview and export.", t: ["result", "final", "clip output", "render output"] },
  "builtin:source": { d: "Start of the clip's graph: outputs the clip's media (video, image, text, 3D or audio) plus audio-analysis ports like waveform, spectrum and beats.", t: ["input", "media", "footage", "clip source", "audio analysis"] },
  "builtin:transform": { d: "Applies the clip's position, scale, rotation, opacity, blend mode, speed and reverse settings to its signal.", t: ["position", "scale", "rotation", "opacity", "blend mode"] },
  "camera.orbit": { d: "Sets the virtual camera for a Voxel Relief in 2D: tilt, yaw, roll, field of view, distance and center; native 3D uses the scene camera.", t: ["camera", "orbit", "view angle", "perspective", "tilt"] },
  "color.luminance-rec709.rgb": { t: ["brightness", "luma", "grayscale", "intensity", "lightness"] },
  "color:alpha-output": { d: "Graph endpoint that receives a key to define transparency; structural in the current realtime grade.", t: ["alpha", "transparency", "matte output", "key output"] },
  "color:combiner": { d: "Recombines separate red, green and blue inputs into one image, the counterpart of Splitter; structural in the current realtime grade.", t: ["rgb combine", "merge channels", "channels", "join"] },
  "color:input": { d: "Fixed start of the color graph that supplies the clip's image to the grade.", t: ["source image", "grade input", "start"] },
  "color:key-mixer": { d: "Combines two key (matte) inputs into one key output; keys are structural and not yet used by the realtime grade.", t: ["matte", "combine keys", "qualifier", "mask mix"] },
  "color:layer-mixer": { d: "Layers two image branches like a layer grading node; the realtime grade currently applies the corrections of both branches in series.", t: ["layer node", "stack grades", "combine branches", "overlay"] },
  "color:output": { d: "Fixed end of the color graph; the image connected here is the graded result passed on to the effects.", t: ["grade output", "result", "end"] },
  "color:parallel-mixer": { d: "Joins two image branches like a parallel grading node; the realtime grade currently applies the corrections of both branches in series.", t: ["parallel node", "mix grades", "combine branches", "blend"] },
  "color:primary": { d: "Main color corrector: exposure, contrast, shadows/highlights, lift/gamma/gain, black/white points, saturation, hue, temperature and tint.", t: ["color correction", "grade", "corrector", "lift gamma gain", "primary grade"] },
  "color:source": { d: "Adds an extra image source node to the color graph; structural in the current realtime grade.", t: ["extra input", "image source", "external source"] },
  "color:splitter": { d: "Splits an image into separate red, green and blue outputs for per-channel grading; structural in the current realtime grade.", t: ["rgb split", "channels", "separate channels", "per channel"] },
  "color:wheels": { d: "Color wheels for lift, gamma, gain and offset per red, green, blue and luma, to balance shadows, midtones and highlights.", t: ["color wheels", "lift gamma gain", "color balance", "grading", "tint shadows"] },
  "control.select.image": { t: ["if", "switch", "branch", "condition", "toggle"] },
  "control:control.audio-envelope": { d: "Outputs an audio clip's loudness over time as 0 to 1 between Silence level and Full level, to make parameters react to sound.", t: ["audio reactive", "loudness", "volume", "beat", "amplitude", "sound"] },
  "control:control.keyframes": { d: "Outputs the value of an existing keyframed parameter curve at the current time so it can be reused or reshaped.", t: ["animation curve", "keyframe", "curve", "reuse animation"] },
  "control:control.lfo": { d: "Outputs a sine wave over time for oscillating parameters; Frequency sets cycles per second, Amplitude and Offset the range, Phase the start.", t: ["oscillator", "sine", "wobble", "modulation", "pulse"] },
  "control:control.remap": { d: "Rescales a number from an input range to an output range, e.g. -1..1 to 0..1; values outside the range extrapolate.", t: ["map range", "rescale", "normalize", "convert range", "fit"] },
  "control:control.time": { d: "Outputs the current time in seconds, measured from the clip start or on the timeline, for driving continuous animation.", t: ["clock", "seconds", "playhead", "time input"] },
  "control:math.add.scalar": { d: "Adds two numbers (A + B), e.g. to offset a control signal.", t: ["plus", "sum", "offset"] },
  "control:math.clamp.scalar": { d: "Limits a number to stay between Min and Max.", t: ["limit", "range", "bound", "min max"] },
  "control:math.multiply.scalar": { d: "Multiplies two numbers (A × B), e.g. to scale a control signal.", t: ["times", "scale", "product", "gain"] },
  "control:values.number": { d: "Outputs a fixed number you set with Value, to drive a parameter or feed other control nodes.", t: ["constant", "value", "number", "static"] },
  "convert.image-to-vec4": { t: ["rgba", "pixel to vector", "color components", "convert"] },
  "data.decode-byte-pixel": { d: "Turns raw memory data into one RGBA pixel, reading 8-bit, 16-bit or 32-bit float values per the Bit Depth setting.", t: ["decode bytes", "raw data", "bit depth", "databending"] },
  "depth.calibrate": { d: "Fits the relative depth map to reference geometry such as the face mesh (or to the image size) so depth lines up in 3D; Depth strength scales it.", t: ["depth scale", "align depth", "calibration", "depth strength"] },
  "depth.estimate": { d: "Estimates a relative depth map from each video frame with an AI model, bright for near and dark for far.", t: ["depth map", "ai depth", "monocular depth", "z-depth", "3d"] },
  "effect:acuarela": { d: "Smears the image with drifting watery noise and fading feedback trails for a flowing watercolor-smoke look; Strength sets the warp, Speed the flow.", t: ["watercolor", "smoke", "liquid", "feedback", "painterly", "flow"] },
  "effect:analog-signal-lab": { d: "Simulates a PAL analog TV and VHS signal chain: RF noise, ghosting, tape wear, tracking errors, chroma bleed and CRT display, each adjustable.", t: ["vhs", "pal", "analog tv", "tape", "crt", "rf noise"] },
  "effect:ascii": { d: "Rebuilds the image from text characters chosen by brightness on a dark background; Cell Size sets character size, Ramp the character set.", t: ["ascii art", "text art", "characters", "terminal", "typography"] },
  "effect:ascii-ghost": { d: "ASCII art whose characters cycle over time and leave fading ghost trails; Cell Size sets character size, Speed the cycling rate.", t: ["ascii art", "text trails", "echo", "afterimage", "characters"] },
  "effect:block-mosaic": { d: "Pixelates into tiles of mixed sizes that reshuffle over time, separated by dark grout lines; Tile Size sets the base tile size.", t: ["mosaic", "tiles", "pixelate", "grid", "grout"] },
  "effect:blockify": { d: "Pixelates the image into large blocks with light posterization; Block Size sets the block size, Amount blends with the original.", t: ["pixelate", "mosaic", "8-bit", "low res", "blocky"] },
  "effect:box-blur": { d: "Blurs the image by averaging a square neighborhood of pixels; Radius sets the blur size.", t: ["average blur", "soften", "mean filter"] },
  "effect:brand-generator": { d: "Block-glyph art whose characters shift in concentric rings around the center, framed by a border, for a logo-like pattern; Cell Size sets glyph size.", t: ["logo", "branding", "graphic pattern", "blocks", "frame"] },
  "effect:bricks": { d: "Rebuilds the image from staggered, beveled toy bricks, each filled with one color; Scale sets the brick size.", t: ["toy bricks", "lego", "mosaic", "3d tiles", "building blocks"] },
  "effect:brightness": { d: "Brightens or darkens the whole image by adding a uniform offset; Amount runs from -1 (darker) to 1 (brighter).", t: ["lighten", "darken", "exposure", "light level"] },
  "effect:bulge": { d: "Magnifies (Amount below 1) or pinches (Amount above 1) the image inside a circular area; Radius and Center set the region.", t: ["pinch", "magnify", "fish bowl", "spherize", "lens bump"] },
  "effect:capsule-cloud": { d: "Places each character inside a faint rounded pill, like a cloud of UI tags, with glyphs cycling over time; Cell Size sets the pill size.", t: ["tags", "pills", "badges", "labels", "ui"] },
  "effect:cctv": { d: "Turns footage into greenish monochrome security-camera video with scanlines, noise and a target box around the tracked subject.", t: ["security camera", "surveillance", "night vision", "monitor", "cctv"] },
  "effect:chroma-key": { d: "Makes a green, blue or custom color transparent; Tolerance sets the key range, Edge Softness the matte edge, Spill Suppression the color fringe.", t: ["green screen", "blue screen", "keying", "matte", "background removal"] },
  "effect:contour": { d: "Draws iso-contour lines where brightness crosses Iso Level, in Line color on Paper; Cell Size sets the line resolution.", t: ["isolines", "topographic", "line art", "marching squares", "outline"] },
  "effect:contour-map": { d: "Turns brightness into banded elevation zones between Ink and Paper with lines at each band, like a topographic map; Scale sets band count.", t: ["topographic", "elevation", "isolines", "posterize", "map"] },
  "effect:contour-type": { d: "Places numeric characters along brightness contour bands and edges, like a typographic topographic map; Cell Size sets character size.", t: ["contour", "topographic", "typography", "isolines", "numbers"] },
  "effect:contrast": { d: "Stretches or flattens tones around mid-gray; Amount above 1 adds punch, below 1 makes the image flatter.", t: ["punch", "flat", "dynamic range", "tone"] },
  "effect:cross-stitch": { d: "Renders the image as X-shaped cross stitches on Paper-colored fabric; Stitch Size sets the stitch grid, Ink tints the thread.", t: ["embroidery", "needlework", "textile", "stitch", "craft"] },
  "effect:crosshatch": { d: "Renders tones as layered pen crosshatching with more line directions in darker areas, in Ink on Paper; Scale sets line spacing.", t: ["hatching", "pen drawing", "sketch", "ink", "etching"] },
  "effect:crt-screen": { d: "Emulates a curved CRT monitor with scanlines, an RGB phosphor mask and subtle flicker; Mask Density sets the mask width, Amount the strength.", t: ["crt", "retro tv", "scanlines", "monitor", "phosphor", "old tv"] },
  "effect:crystal": { d: "Refracts the image through a grid of tilted glass facets with a gentle shimmer; Scale sets facet count, Amount the refraction.", t: ["glass", "prism", "refraction", "faceted", "frosted glass"] },
  "effect:data-hatch": { d: "Mixes cycling characters with diagonal hatching that thickens in darker areas; Cell Size sets character size, Speed the cycling.", t: ["hatching", "data art", "binary", "crosshatch"] },
  "effect:dither": { d: "Applies ordered Bayer dithering that reduces colors to a few levels per channel; Pixel Size sets the dither grain, Amount blends with the original.", t: ["bayer", "ordered dither", "retro", "8-bit", "quantize"] },
  "effect:dither-studio": { d: "Reduces the image to two ink colors using a selectable dither pattern (Bayer 2, Bayer 4 or Checker); Kernel picks the pattern, Scale its size.", t: ["1-bit", "two-tone", "bayer", "monochrome dither", "duotone"] },
  "effect:dither-text": { d: "Character art dithered with a checkerboard threshold and flickering noise so glyphs show mostly in brighter cells; Cell Size sets character size.", t: ["text dither", "ascii", "characters", "noise", "typography"] },
  "effect:drift-lines": { d: "Shifts horizontal bands sideways in a wavy animated drift and shades them into lines; Scale sets band height, Amount the drift.", t: ["horizontal lines", "wobble", "scanlines", "interlace", "wave"] },
  "effect:edge-detect": { d: "Replaces the image with a black-and-white edge map, white lines where brightness changes sharply (or inverted); Strength sets line intensity.", t: ["sobel", "outline", "edges", "line drawing", "sketch"] },
  "effect:embroidery": { d: "Covers the image in wavy animated thread rows tinted with the Ink color for a knitted fabric look; Scale sets the stitch size.", t: ["knit", "textile", "thread", "fabric", "yarn"] },
  "effect:exposure": { d: "Adjusts exposure in camera stops, with an additive Offset and a Gamma curve for midtones.", t: ["ev", "stops", "gamma", "brightness", "overexpose"] },
  "effect:face-cables": { d: "Hangs physics-simulated ropes between chosen face landmarks that swing with gravity, wind and head motion; baked from precise face tracking.", t: ["ropes", "cables", "physics", "face tracking", "wires", "strings"] },
  "effect:film-prism": { d: "Adds animated radial chromatic fringing toward the edges plus fine film grain; Amount sets the fringe strength.", t: ["chromatic aberration", "film", "grain", "color fringe", "lens"] },
  "effect:fisheye": { d: "Bends the image through a fisheye lens, or straightens one with negative Strength, with projection, edge, aberration and vignette options.", t: ["lens distortion", "barrel", "wide angle", "defisheye", "lens correction", "action cam"] },
  "effect:gaussian-blur": { d: "Softens the image with a smooth Gaussian blur; Radius sets blur size, Samples the quality.", t: ["soften", "defocus", "smooth", "out of focus"] },
  "effect:glass-dispersion": { d: "Splits red and blue in random per-cell directions that pulse over time, like light through pixelated glass; Scale sets cell size, Amount the spread.", t: ["chromatic aberration", "rgb split", "glass", "prism", "dispersion"] },
  "effect:glitch": { d: "Flickers random horizontal bands sideways with a slight red/blue channel split for a digital glitch; Scale sets band count, Amount the shift.", t: ["glitch", "vhs", "rgb split", "datamosh", "digital distortion"] },
  "effect:glitch-grid": { d: "Randomly jumps grid cells sideways in flickering bursts for a blocky digital glitch; Scale sets cell size, Amount the displacement.", t: ["glitch", "datamosh", "digital error", "block shift", "corruption"] },
  "effect:glow": { d: "Adds a soft bloom around areas brighter than Threshold; Amount sets glow intensity, Radius and Softness its spread.", t: ["bloom", "halo", "light glow", "dreamy", "soft light"] },
  "effect:glyph-matrix": { d: "Character art whose glyphs sweep diagonally through the character ramp over time, like a scrolling data wave; Speed sets the sweep rate.", t: ["ascii animation", "characters", "data wave", "text"] },
  "effect:grain": { d: "Adds animated film-grain noise that is stronger in shadows than highlights; Amount sets intensity, Size the grain size.", t: ["film grain", "noise", "analog", "texture", "grit"] },
  "effect:grid-glyph": { d: "ASCII-style character art with a faint grid line drawn around every cell; Cell Size sets the grid and character size.", t: ["ascii", "grid", "text art", "cells"] },
  "effect:halftone": { d: "Turns the image into rotated halftone dots that grow in dark areas, drawn in Ink on Paper; Scale sets dot spacing, Angle the screen angle.", t: ["dots", "print", "comic", "newspaper", "screen"] },
  "effect:hand-particles": { d: "Adds drifting glowing particles around tracked hands in the Overlay color; Particle Source picks fingertips, all landmarks or hand centers.", t: ["hands", "particles", "fingertips", "magic", "sparkles"] },
  "effect:holo": { d: "Overlays an animated holographic interference shimmer between two spectrum colors, stronger on edges; Spectrum A and B set the colors.", t: ["hologram", "iridescent", "foil", "rainbow", "shimmer"] },
  "effect:hud-tracker": { d: "Overlays a sci-fi HUD with a corner-bracket target box around the tracked subject, landmark dots and a sweeping scan line in the Overlay color.", t: ["hud", "target lock", "sci-fi", "bounding box", "tracking overlay"] },
  "effect:hue-shift": { d: "Rotates all colors around the color wheel; Shift sets how far hues move (0 to 1 is a full turn).", t: ["hue rotate", "color shift", "recolor", "color wheel"] },
  "effect:inscribe": { d: "Draws characters only along brightness edges over a darkened image, like text etched into the outlines; Cell Size sets character size.", t: ["edge text", "outline", "etched", "engraved text", "typography"] },
  "effect:invert": { d: "Inverts all colors to produce a photographic negative.", t: ["negative", "reverse colors", "inverse"] },
  "effect:kaleidoscope": { d: "Mirrors wedge-shaped slices around the center into a symmetric kaleidoscope pattern; Segments sets slice count, Rotation turns it.", t: ["mandala", "symmetry", "mirror", "psychedelic"] },
  "effect:kilim": { d: "Overlays a woven diamond-and-stripe carpet pattern in two colors, shaded by image brightness; Scale sets the motif size.", t: ["carpet", "rug", "textile", "woven pattern", "tribal"] },
  "effect:kinetic-trace": { d: "Leaves fading light trails behind moving content that drift with the tracked motion, tinted with the Overlay color around the subject.", t: ["motion trails", "echo", "afterimage", "streaks", "ghosting"] },
  "effect:levels": { d: "Remaps input black and white points, midtone gamma and output range, like a classic Levels adjustment.", t: ["black point", "white point", "gamma", "tonal range", "histogram"] },
  "effect:matrix": { d: "Covers the image with falling green code characters with bright moving heads, like digital rain; Speed sets the fall rate, Cell Size the glyph size.", t: ["digital rain", "code rain", "hacker", "green code", "cyber"] },
  "effect:memory-leak": { d: "Shows raw leftover bytes from the editor's decoder memory as glitchy pixel data; Block Width sets pixel size, Bit Depth how bytes become color.", t: ["databending", "raw memory", "glitch", "data art", "corruption", "noise"] },
  "effect:mirror": { d: "Mirrors the left half onto the right (Horizontal) and/or the top half onto the bottom (Vertical) for symmetric images.", t: ["symmetry", "flip", "reflect", "reflection"] },
  "effect:motion-blur": { d: "Smears the image along one straight direction like fast camera movement; Amount sets streak length, Angle the direction.", t: ["directional blur", "linear blur", "speed", "streak"] },
  "effect:number-field": { d: "Renders the image as a field of digits chosen by brightness, colored in five steps between Dark and Light; Cell Size sets digit size.", t: ["numbers", "digits", "paint by numbers", "data art"] },
  "effect:outline": { d: "Turns the image into an edge drawing: brightness edges in Ink on Paper with a subtle pulse; Amount blends with the original.", t: ["edges", "line drawing", "sketch", "ink outline", "trace"] },
  "effect:paper-print": { d: "Maps brightness to a grainy two-color press print between Ink and Paper; Press Grain sets the size of the noise texture.", t: ["print", "letterpress", "grain", "duotone", "paper"] },
  "effect:pattern-halftone": { d: "Halftone screen of circle, diamond or line marks sized by image darkness, in Ink on Paper; Shape picks the mark, Scale the cell size.", t: ["line screen", "diamond dots", "print", "halftone", "engraving"] },
  "effect:pixel-code": { d: "Replaces the image with random code characters (binary by default) tinted from deep blue to mint green by brightness; Cell Size sets character size.", t: ["binary", "code", "data", "hacker", "digits"] },
  "effect:pixel-dither": { d: "Renders glowing neon characters with soft cell halos, colored from Dark to Light by brightness; Cell Size sets character size.", t: ["neon", "glow", "led", "pixel", "glyphs"] },
  "effect:flocking": { d: "Adds a boids swarm simulated in 3D above the clip, driven by an editable node graph of particles, forces and render nodes; the clip image stays visible underneath.", t: ["flock", "boids", "swarm", "particles", "birds", "fish", "simulation"] },
  "effect:pixel-particle-disintegrate": { d: "Breaks the image into pixel particles that blow away in 3D with wind, curl and gravity as Progress goes from 0 to 1; Cell Size sets particle size.", t: ["disintegrate", "dissolve", "dust", "particles", "snap", "outro", "vanish"] },
  "effect:pixel-poster": { d: "Pixelates the image into blocks and posterizes each to a few color levels; Block Size sets the pixel size.", t: ["pixelate", "posterize", "8-bit", "retro", "mosaic"] },
  "effect:pixel-sort": { d: "Sorts pixels by brightness within short horizontal segments where they exceed Threshold, for glitchy smeared streaks; Segment Size sets run length.", t: ["glitch", "sorting", "datamosh", "smear", "streaks"] },
  "effect:pixelate": { d: "Reduces the image to large square pixels; Pixel Size sets the block size.", t: ["mosaic", "censor", "8-bit", "low res", "blocky"] },
  "effect:posterize": { d: "Reduces each color channel to a few levels for flat, poster-like color bands; Levels sets the number of steps.", t: ["color reduction", "banding", "flat color", "pop art"] },
  "effect:quadtree-zoom": { d: "Splits the image into adaptive square blocks, small where detail is high and large in flat areas; Minimum Cell and Detail Threshold control the split.", t: ["quadtree", "adaptive pixelate", "mosaic", "blocks", "subdivision"] },
  "effect:radial-blur": { d: "Streaks the image along lines radiating from a center point, growing stronger toward the edges; Amount sets strength, Center X/Y the origin.", t: ["radial streaks", "center blur", "light rays", "burst"] },
  "effect:rain-reveal": { d: "Pours falling streaks of the Overlay color over the scene, with less rain over the tracked subject and a slightly dimmed background.", t: ["rain", "streaks", "reveal", "spotlight", "weather"] },
  "effect:retro-matrix": { d: "Scrolls amber monochrome terminal characters vertically with scanlines, like an old phosphor display; Speed sets the scroll rate.", t: ["amber terminal", "retro computer", "crt", "phosphor", "numbers"] },
  "effect:rgb-split": { d: "Offsets the red and blue channels in opposite directions for a color-fringe look; Amount sets the offset, Angle the direction.", t: ["chromatic aberration", "color fringe", "channel shift", "glitch", "anaglyph"] },
  "effect:ribbon-scan": { d: "Sweeps rolling horizontal ribbons through the image that bend it sideways as they scroll; Scale sets ribbon count, Speed the scroll rate.", t: ["scan", "roll", "wave", "vhs", "distortion"] },
  "effect:riso": { d: "Simulates two-ink risograph printing on cream paper with misregistered layers; Registration sets the offset, Dark and Warm Ink pick the colors.", t: ["risograph", "screen print", "duotone", "misregistration", "print"] },
  "effect:riso-glow": { d: "Two-ink risograph print look with a pulsing glow added to the inks; Shadow and Glow Ink set the colors, Speed the pulse rate.", t: ["risograph", "duotone", "glow", "print", "neon print"] },
  "effect:rom1": { d: "Frozen earlier version of Acuarela: a watery watercolor-smoke smear with feedback trails and slower drifting noise, kept for stable looks.", t: ["watercolor", "smoke", "liquid", "feedback", "acuarela"] },
  "effect:saturation": { d: "Increases or reduces color intensity; Amount 0 gives grayscale, 1 is unchanged and higher values oversaturate.", t: ["color intensity", "desaturate", "grayscale", "black and white", "vivid"] },
  "effect:scanlines": { d: "Overlays darkened horizontal lines that can scroll; Density sets line count, Opacity their darkness, Scroll Speed the movement.", t: ["crt", "tv lines", "retro", "interlace", "monitor"] },
  "effect:scatter-mosaic": { d: "Breaks the image into tiles that sample from randomly jittered, drifting positions; Scale sets tile size, Amount the scatter distance.", t: ["mosaic", "tiles", "scatter", "jitter", "shuffle"] },
  "effect:sharpen": { d: "Increases local edge contrast so detail looks crisper; Amount sets strength, Radius the size of detail enhanced.", t: ["unsharp mask", "crisp", "detail", "clarity"] },
  "effect:slit-scan": { d: "Shows each region of the frame from a different moment in time, smearing motion into warped shapes; Profile sets the scan pattern, Delay the time span.", t: ["time displacement", "time warp", "temporal", "slitscan", "rolling shutter"] },
  "effect:splat-exploration": { d: "Stylizes a Gaussian splat clip by layering the splat with stretched light streaks, drifting particles and a wireframe surface mesh.", t: ["gaussian splat", "3d scan", "particles", "wireframe", "point cloud"] },
  "effect:stardust": { d: "Scatters sparkling star particles in the Overlay color around the tracked landmarks, or a ring around the subject; Speed sets the drift.", t: ["sparkles", "glitter", "particles", "magic", "stars"] },
  "effect:stitch-poster": { d: "Combines character art with cross-stitch X marks that get denser in dark areas over a paper-tinted background; Cell Size sets stitch size.", t: ["cross stitch", "embroidery", "poster", "textile", "symbols"] },
  "effect:subject": { d: "Spotlights the tracked subject by keeping areas around face, body and hand landmarks bright while dimming the rest; needs landmark tracking.", t: ["spotlight", "focus", "person", "highlight subject", "landmarks"] },
  "effect:symbol-matrix": { d: "Symbol character art where each cell randomly swaps glyphs and pulses in brightness; Speed controls the flicker rate.", t: ["symbols", "flicker", "glyphs", "twinkle", "text"] },
  "effect:temperature": { d: "Warms or cools the image by shifting red against blue; Tint shifts between green and magenta.", t: ["white balance", "warm", "cool", "tint", "color cast"] },
  "effect:threshold": { d: "Converts the image to pure black and white at a brightness cutoff; Level sets the threshold.", t: ["black and white", "binary", "1-bit", "high contrast", "bitmap"] },
  "effect:time-stack": { d: "Layers several time-delayed copies of the clip with a blend mode for stroboscopic echo trails; Instances sets the copy count, Time offset the delay.", t: ["echo", "stroboscopic", "motion trail", "chronophotography", "frame blending", "ghosting"] },
  "effect:tone-geometry": { d: "Replaces the image with a grid of squares, circles or triangles sized by darkness, in Ink on Paper; Shape picks the form, Scale the cell size.", t: ["geometric halftone", "shapes", "dots", "pattern", "grid"] },
  "effect:tracked-scene": { d: "Draws tracked face landmarks as dots connected by lines in the Overlay color, like a motion-capture mesh.", t: ["face mesh", "motion capture", "landmarks", "wireframe", "tracking overlay"] },
  "effect:twirl": { d: "Swirls the image around a center point, strongest at the center and fading out at Radius; Amount sets twist strength and direction.", t: ["swirl", "vortex", "spiral", "whirlpool"] },
  "effect:ui-collage": { d: "Turns the image into boxed UI-like cells with characters, borders and cursor dots that shuffle over time; Cell Size sets the box size.", t: ["ui", "interface", "collage", "binary", "widgets"] },
  "effect:vector-tiling": { d: "Redraws the image as rows of engraved wavy lines whose wave depth follows darkness, in Ink on Paper; Scale sets line spacing, Angle the direction.", t: ["engraving", "line art", "banknote", "etching", "woodcut"] },
  "effect:vibrance": { d: "Boosts or mutes muted colors more than already-saturated ones for a gentler saturation change; Amount sets direction and strength.", t: ["smart saturation", "color boost", "skin tones", "vivid"] },
  "effect:vignette": { d: "Darkens the frame toward its edges; Amount sets darkness, while Size, Softness and Roundness shape the falloff.", t: ["edge darkening", "corners", "lens vignette", "frame"] },
  "effect:voronoi": { d: "Shatters the image into slowly drifting Voronoi cells, each filled with one sampled color and subtly outlined; Scale sets cell size.", t: ["cells", "stained glass", "crystallize", "mosaic", "cellular"] },
  "effect:voxel-relief": { d: "Extrudes the image into 3D blocks whose height follows brightness, seen through an orbitable camera; Columns sets block count, Height the depth.", t: ["3d", "extrude", "blocks", "heightmap", "voxels", "relief"] },
  "effect:wave": { d: "Ripples the image with sine waves along both axes; the Amp controls set wave height, the Freq controls the number of waves.", t: ["ripple", "wobble", "wavy", "water", "underwater"] },
  "effect:wave-lines": { d: "Draws wavy horizontal lines in Ink on Paper whose waves bend with image brightness; Scale sets line density, Amount the wave strength.", t: ["line art", "engraving", "waves", "op art", "stripes"] },
  "effect:word-mosaic": { d: "Builds the image from rows of characters joined by thin connector strokes in brighter areas so they read like words; Cell Size sets letter size.", t: ["text mosaic", "typography", "words", "letters", "ascii"] },
  "effect:zoom-blur": { d: "Creates a zoom-burst blur that streaks the image outward from a center point, as if zooming during the exposure; Amount sets streak length.", t: ["zoom burst", "speed", "punch in", "radial blur", "warp speed"] },
  "field.noise2d": { t: ["value noise", "perlin", "random pattern", "noise texture", "procedural"] },
  "fisheye.aa": { d: "Picks the sub-pixel sample position for each anti-aliasing pass of Fisheye Lens, based on the Edge Sampling count.", t: ["anti-aliasing", "supersampling", "fisheye", "subpixel"] },
  "fisheye.channel-resolve": { d: "Rebuilds one image from separately sampled red, green and blue channels.", t: ["combine channels", "rgb merge", "chromatic aberration", "fisheye"] },
  "fisheye.chroma": { d: "Samples red, green and blue at slightly different lens radii to add color fringes toward the lens edge.", t: ["chromatic aberration", "color fringe", "rgb split", "fisheye"] },
  "fisheye.edge-coordinates": { d: "Adjusts sample positions outside the frame by the Frame Edges mode: clamp, mirror or repeat.", t: ["edge mode", "wrap", "mirror", "clamp", "fisheye"] },
  "fisheye.edge-coverage": { d: "Samples the image at the adjusted positions and fades areas outside the frame to transparent using Edge Feather.", t: ["edge fade", "feather", "frame edges", "fisheye"] },
  "fisheye.edges": { d: "Decides what appears beyond the source frame: transparent, clamped, mirrored or repeated pixels, with a soft Edge Feather.", t: ["frame edges", "edge mode", "wrap", "mirror", "fisheye"] },
  "fisheye.jitter-pattern": { d: "Provides the eight fixed sub-pixel offsets Fisheye Lens uses to smooth edges, chosen by sample index.", t: ["anti-aliasing", "jitter", "sample offsets", "fisheye"] },
  "fisheye.lens": { d: "Works out where each output pixel samples the source through the fisheye lens from center, field of view, projection, strength, zoom and squeeze.", t: ["lens mapping", "distortion", "fisheye", "barrel", "projection"] },
  "fisheye.lens-coordinates": { d: "Converts an image position into lens space (distance and direction from the lens center) using center, aspect, squeeze, rotation and lens radius.", t: ["lens space", "polar", "fisheye", "coordinates"] },
  "fisheye.lens-coverage": { d: "Computes the inside-the-lens mask, hard and feathered by Lens Feather, from the distance to the lens edge.", t: ["lens mask", "circle mask", "feather", "fisheye"] },
  "fisheye.projection-model": { d: "Computes how the chosen projection (equidistant, equisolid, stereographic or orthographic) bends a lens radius for the field of view.", t: ["projection", "lens model", "fisheye", "field of view"] },
  "fisheye.radius-curve": { d: "Turns the projected radius into the final sampling radius, blending by Strength and applying Curve Bias and Zoom.", t: ["lens curve", "zoom", "distortion strength", "fisheye"] },
  "fisheye.resolve": { d: "Final fisheye step: applies vignette and lens feather, shows the original or transparency outside the lens, and averages the samples.", t: ["fisheye output", "lens composite", "vignette", "feather"] },
  "fisheye.sample-average": { d: "Averages the anti-aliasing samples into the final smooth fisheye pixel.", t: ["anti-aliasing", "average", "supersampling", "fisheye"] },
  "fisheye.vignette": { d: "Darkens the fisheye image toward the lens rim; Lens Vignette sets strength, Vignette Softness the falloff.", t: ["vignette", "edge darkening", "lens falloff", "fisheye"] },
  "forces.curl-noise": { d: "Swirls released particles through a curl noise field; Turbulence adds finer jitter.", t: ["curl", "swirl", "noise force", "turbulence", "particles"] },
  "forces.scatter": { d: "Pushes released particles apart in the image plane (Spread), toward the camera (Depth) and spins them (Spin).", t: ["scatter", "explode", "spread", "spin", "particles"] },
  "forces.wind-gusts": { d: "Blows released particles along a direction with uneven gusts across the image.", t: ["wind", "gusts", "blow away", "direction", "particles"] },
  "geometry.depth": { d: "Builds a 3D surface mesh from a calibrated depth map, textured with the source image.", t: ["depth mesh", "displacement", "3d surface", "relief", "heightmap"] },
  "geometry.face": { d: "Builds a 3D face mesh from tracked face landmarks, textured with the source image.", t: ["face mesh", "landmarks to mesh", "3d face", "face geometry"] },
  "geometry.jump-flood": { d: "Spreads the nearest seed point to every pixel, turning scattered seeds into complete Voronoi cells.", t: ["voronoi", "nearest point", "distance field", "cells", "flood fill"] },
  "geometry.marching-squares-topology": { d: "Finds up to two contour line segments in a grid cell from its four corner values, used to draw iso-contour lines.", t: ["contour", "isolines", "marching squares", "line segments"] },
  "geometry.merge-surface": { d: "Stitches a primary mesh such as the face into a background depth surface, cutting out its outline and blending the seam; Seam blend sets smoothness.", t: ["merge meshes", "stitch", "seam", "combine surfaces"] },
  "geometry.voronoi-seeds": { d: "Places one randomly jittered, slowly drifting seed point per cell as starting points for a Voronoi pattern; Cell Size sets the spacing.", t: ["voronoi", "seeds", "cells", "random points", "jitter"] },
  "glyph.atlas": { d: "Provides the character sheet for glyph effects, drawn from the effect's Ramp and Font settings, plus its glyph count and grid size.", t: ["glyph atlas", "characters", "font", "ascii", "text sheet"] },
  "image.mask-overlay": { t: ["mask preview", "highlight", "tint mask", "overlay color", "debug mask"] },
  "image.normalized-uv": { t: ["uv", "coordinates", "position", "screen position", "texcoord"] },
  "image.sample": { t: ["texture lookup", "uv lookup", "resample", "displace", "read pixel"] },
  "image.temporal-smooth": { t: ["flicker", "stabilize mask", "denoise over time", "deflicker", "temporal blur", "smoothing"] },
  "image.timeline-time": { t: ["time", "seconds", "clock", "animate", "playhead"] },
  "light.relief": { d: "Lights the relief with one directional light plus ambient fill; Light Angle and Elevation set its direction, optionally following the camera.", t: ["lighting", "sun", "shading", "directional light", "ambient"] },
  "math.abs": { d: "Takes the absolute value of a field per Voxel Relief cell, turning negative values positive.", t: ["absolute", "positive", "magnitude", "height field"] },
  "math.abs.audio": { d: "Makes every audio sample positive (full-wave rectification), adding harmonics and a DC offset.", t: ["rectify", "absolute", "distortion", "audio math"] },
  "math.add": { d: "Adds two fields per Voxel Relief cell (A + B) to shape the height field; unconnected inputs use their number controls.", t: ["plus", "sum", "height field", "voxel"] },
  "math.add.audio-audio": { d: "Adds two audio signals sample by sample, mixing them together.", t: ["plus", "sum", "mix signals", "audio math"] },
  "math.add.audio-scalar": { d: "Adds A and B for every audio sample; a number input applies the same offset to all samples.", t: ["plus", "sum", "dc offset", "audio math"] },
  "math.add.scalar": { d: "Adds two numbers (A + B).", t: ["plus", "sum", "offset"] },
  "math.add.scalar-audio": { d: "Adds A and B for every audio sample; a number input applies the same offset to all samples.", t: ["plus", "sum", "dc offset", "audio math"] },
  "math.clamp": { d: "Limits a field to between Minimum and Maximum per Voxel Relief cell.", t: ["limit", "range", "bound", "height field"] },
  "math.clamp.audio-audio-audio": { d: "Limits each audio sample between Min and Max, a hard clipper; each bound can be a number or audio.", t: ["hard clip", "limit", "clipper", "audio math"] },
  "math.clamp.audio-audio-scalar": { d: "Limits each audio sample between Min and Max, a hard clipper; each bound can be a number or audio.", t: ["hard clip", "limit", "clipper", "audio math"] },
  "math.clamp.audio-scalar-audio": { d: "Limits each audio sample between Min and Max, a hard clipper; each bound can be a number or audio.", t: ["hard clip", "limit", "clipper", "audio math"] },
  "math.clamp.audio-scalar-scalar": { d: "Limits each audio sample between Min and Max, a hard clipper; each bound can be a number or audio.", t: ["hard clip", "limit", "clipper", "audio math"] },
  "math.clamp.scalar": { t: ["limit", "range", "bound", "min max", "saturate"] },
  "math.clamp.scalar-audio-audio": { d: "Limits the value between Min and Max for each audio sample, a hard clipper; each input can be a number or audio.", t: ["hard clip", "limit", "clipper", "audio math"] },
  "math.clamp.scalar-audio-scalar": { d: "Limits the value between Min and Max for each audio sample, a hard clipper; each input can be a number or audio.", t: ["hard clip", "limit", "clipper", "audio math"] },
  "math.clamp.scalar-scalar-audio": { d: "Limits the value between Min and Max for each audio sample, a hard clipper; each input can be a number or audio.", t: ["hard clip", "limit", "clipper", "audio math"] },
  "math.constant": { d: "Outputs one fixed value for every Voxel Relief cell, e.g. as a base height or factor for other field math.", t: ["constant", "value", "height field", "voxel"] },
  "math.cos.audio": { d: "Applies a cosine to each audio sample, a wave-shaping distortion that also shifts the signal.", t: ["waveshaper", "cosine", "distortion", "audio math"] },
  "math.divide": { d: "Divides field A by B per Voxel Relief cell; dividing by nearly zero returns 0.", t: ["divide", "ratio", "quotient", "height field", "voxel"] },
  "math.divide-ieee.audio-audio": { d: "Divides audio A by audio B sample by sample without protection against division by zero.", t: ["divide", "ratio", "audio math"] },
  "math.divide-ieee.audio-scalar": { d: "Divides every audio sample A by B without protection against division by zero; a number input applies to all samples.", t: ["divide", "attenuate", "audio math"] },
  "math.divide-ieee.scalar-audio": { d: "Divides A by every audio sample B without protection against division by zero; a number input applies to all samples.", t: ["divide", "reciprocal", "audio math"] },
  "math.exp2.scalar": { d: "Returns 2 raised to the input number (2^x), e.g. for exposure stops.", t: ["power of two", "exponent", "stops", "2^x"] },
  "math.floor.audio": { d: "Rounds each audio sample down to a whole number; on normal audio this gives a harsh square-like signal.", t: ["quantize", "bitcrush", "distortion", "audio math"] },
  "math.fract.audio": { d: "Keeps only the fractional part of each audio sample (x minus floor x), a harsh wrap-around distortion.", t: ["wrap", "distortion", "fold", "audio math"] },
  "math.fract.scalar": { d: "Returns the fractional part of a number (x minus floor x), e.g. to make a repeating 0 to 1 ramp.", t: ["fraction", "wrap", "modulo", "repeat", "sawtooth"] },
  "math.max": { d: "Keeps the larger of two fields per Voxel Relief cell, e.g. to set a minimum height.", t: ["maximum", "higher", "floor", "height field"] },
  "math.max.audio-audio": { d: "Keeps the larger of two audio signals for each sample.", t: ["maximum", "combine", "audio math"] },
  "math.max.audio-scalar": { d: "Keeps the larger of A and B for each audio sample, e.g. to clip the signal from below at a floor.", t: ["maximum", "floor clip", "audio math"] },
  "math.max.scalar-audio": { d: "Keeps the larger of A and B for each audio sample, e.g. to clip the signal from below at a floor.", t: ["maximum", "floor clip", "audio math"] },
  "math.min": { d: "Keeps the smaller of two fields per Voxel Relief cell, e.g. to cap heights.", t: ["minimum", "lower", "cap", "height field"] },
  "math.min.audio-audio": { d: "Keeps the smaller of two audio signals for each sample.", t: ["minimum", "combine", "audio math"] },
  "math.min.audio-scalar": { d: "Keeps the smaller of A and B for each audio sample, e.g. to clip peaks at a ceiling.", t: ["minimum", "ceiling clip", "audio math"] },
  "math.min.scalar-audio": { d: "Keeps the smaller of A and B for each audio sample, e.g. to clip peaks at a ceiling.", t: ["minimum", "ceiling clip", "audio math"] },
  "math.mix.audio-audio-audio": { d: "Crossfades between audio A and B using a third audio signal as T for each sample.", t: ["crossfade", "modulation", "lerp", "audio math"] },
  "math.mix.audio-audio-scalar": { d: "Crossfades between audio A and B by T for each sample (0 = A, 1 = B).", t: ["crossfade", "blend", "lerp", "dry wet", "audio math"] },
  "math.mix.audio-scalar-audio": { d: "Crossfades between A and B using an audio signal as T for each sample (0 = A, 1 = B).", t: ["crossfade", "modulation", "lerp", "audio math"] },
  "math.mix.audio-scalar-scalar": { d: "Crossfades between A and B by T for each audio sample (0 = A, 1 = B); inputs can be numbers or audio.", t: ["crossfade", "blend", "lerp", "dry wet", "audio math"] },
  "math.mix.scalar": { t: ["lerp", "blend", "interpolate", "crossfade", "linear interpolation"] },
  "math.mix.scalar-audio-audio": { d: "Crossfades between A and B using an audio signal as T for each sample (0 = A, 1 = B).", t: ["crossfade", "modulation", "lerp", "audio math"] },
  "math.mix.scalar-audio-scalar": { d: "Crossfades between A and B by T for each audio sample (0 = A, 1 = B); inputs can be numbers or audio.", t: ["crossfade", "blend", "lerp", "dry wet", "audio math"] },
  "math.mix.scalar-scalar-audio": { d: "Crossfades between A and B using an audio signal as T for each sample, like amplitude modulation.", t: ["crossfade", "modulation", "lerp", "audio math"] },
  "math.multiply": { d: "Multiplies two fields per Voxel Relief cell (A × B), e.g. to scale brightness-driven heights.", t: ["times", "scale", "product", "height field", "voxel"] },
  "math.multiply.audio-audio": { d: "Multiplies two audio signals sample by sample, like ring modulation.", t: ["ring modulation", "am", "modulate", "audio math"] },
  "math.multiply.audio-scalar": { d: "Multiplies every audio sample by a number, acting as a gain control.", t: ["gain", "volume", "scale", "audio math"] },
  "math.multiply.scalar": { d: "Multiplies two numbers (A × B).", t: ["times", "scale", "product", "gain"] },
  "math.multiply.scalar-audio": { d: "Multiplies every audio sample by a number, acting as a gain control.", t: ["gain", "volume", "scale", "audio math"] },
  "math.power": { d: "Raises field A to the power B per Voxel Relief cell to reshape height contrast.", t: ["exponent", "pow", "gamma", "curve", "height field"] },
  "math.reciprocal.scalar": { d: "Returns 1 divided by the input number.", t: ["inverse", "one over", "1/x"] },
  "math.sin": { d: "Applies a sine (input in radians) to a field per Voxel Relief cell for wavy, repeating height patterns.", t: ["sine", "wave", "periodic", "height field"] },
  "math.sin.audio": { d: "Applies a sine to each audio sample, a soft wave-folding distortion.", t: ["wavefolder", "sine shaper", "distortion", "audio math"] },
  "math.smoothstep.scalar": { t: ["ease", "soft threshold", "hermite", "smooth ramp", "falloff"] },
  "math.subtract": { d: "Subtracts field B from A per Voxel Relief cell, e.g. to lower or invert heights.", t: ["minus", "difference", "height field", "voxel"] },
  "math.subtract.audio-audio": { d: "Subtracts audio B from audio A sample by sample, e.g. to cancel shared content between two signals.", t: ["minus", "difference", "phase cancel", "audio math"] },
  "math.subtract.audio-scalar": { d: "Subtracts B from A for every audio sample; a number input applies the same value to all samples.", t: ["minus", "difference", "dc offset", "audio math"] },
  "math.subtract.scalar-audio": { d: "Subtracts B from A for every audio sample; a number input applies the same value to all samples.", t: ["minus", "difference", "invert", "audio math"] },
  "media.source": { d: "Provides the clip's video frames as the image input for face tracking and depth analysis.", t: ["video input", "footage", "frames", "source"] },
  "noise.hash2d.vec2": { t: ["random", "hash", "noise", "pseudo random", "white noise"] },
  "render.cables": { d: "Draws the simulated cables as shaded, rounded tubes with attachment rings, optionally in native 3D or with 2D face shadows.", t: ["cable render", "tubes", "ropes", "shading", "wires"] },
  "render.pixel-particles": { d: "Draws pixel particles as the clip image with square, soft or shard shapes; muting it shows the input unchanged.", t: ["particle render", "disintegrate", "dust", "vanish", "points"] },
  "scene.output": { d: "End point of the cable scene graph; the scene connected here is what the clip renders.", t: ["output", "result", "final scene"] },
  "select.scalar": { t: ["if", "switch", "branch", "condition", "ternary"] },
  "simulation.image-particles": { d: "Cuts the image into a grid of colored pixel particles; Cell Size sets the particle size.", t: ["pixels to particles", "disintegrate", "emitter", "dust", "vanish"] },
  "simulation.particle-motion": { d: "Moves released particles with the connected forces such as scatter, wind, curl noise and gravity.", t: ["particle simulation", "forces", "motion", "dynamics"] },
  "simulation.particle-release": { d: "Releases pixel particles over the image as Progress goes from 0 to 1, staggered by a sweep and the image brightness.", t: ["vanish", "disintegrate", "dissolve", "thanos snap", "outro", "progress"] },
  "simulation.rope": { d: "Simulates hanging ropes between anchor points with gravity, inertia, damping and length limits, reacting to connected forces, drag and colliders.", t: ["rope physics", "cables", "dynamics", "hanging wires", "strings"] },
  "source.memory-window": { d: "Reads the Memory Leak effect's selected block of raw memory as data, with its size and availability.", t: ["raw memory", "bytes", "databending", "memory leak"] },
  "texture.image": { d: "Turns the connected video frame into a texture that materials and luminance nodes can sample, using the connected UV mapping.", t: ["texture", "image map", "material input", "footage texture"] },
  "texture.uv": { d: "Scales and offsets the texture coordinates used to map an image onto a surface; chained UV nodes combine in order.", t: ["uv", "tiling", "texture offset", "texture scale", "mapping"] },
  "tracking.anchors": { d: "Picks the face landmark positions used as cable start and end points, such as mouth corners, irises or brows.", t: ["attachment points", "anchor", "landmarks", "cable ends"] },
  "tracking.face": { d: "Detects the face in each video frame with MediaPipe and outputs its landmark points for cables and face meshes.", t: ["face tracking", "landmarks", "mediapipe", "face detection", "facial points"] },
  "values.number": { d: "Outputs a fixed number you set with Value, for driving node inputs or parameters.", t: ["constant", "number", "value", "scalar", "float"] },
  "values.oscillator": { d: "Outputs a sine wave over time, Offset + Amplitude × sin(time × Frequency), for pulsing or swinging values.", t: ["lfo", "sine", "wave", "oscillate", "pulse", "wobble"] },
  "vector.combine.vec2": { t: ["make vector", "join xy", "compose", "pack"] },
  "vector.split.vec2": { t: ["separate xy", "decompose", "components", "break vector"] },
};

export interface CatalogText { description?: string; tags: readonly string[] }
export function catalogText(id: string): CatalogText {
  const entry = CATALOG_TEXT[id];
  return { description: entry?.d, tags: entry?.t ?? [] };
}
