export const currentWorkflowGetStateHardTargets = [
  // Release 3.1.3 added imperative UI event handlers and cross-store tracking,
  // terrain, annotation, and camera-output workflows. These reads must observe
  // state at action time to avoid stale React closures or partial transactions.
  // They remain exact hard targets instead of adapter exemptions so every new
  // call site still requires an explicit review and a matching cap change.
  { path: 'src/App.tsx', maxCurrentHits: 1 },
  { path: 'src/components/common/EditorPlaybackRuntimeHost.tsx', maxCurrentHits: 1 },
  { path: 'src/components/dock/useMobilePreviewLayoutFit.ts', maxCurrentHits: 1 },
  { path: 'src/components/export/runners/hapExportRunner.ts', maxCurrentHits: 1 },
  { path: 'src/components/panels/annotations/AnnotationsPanel.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/color-workspace/ColorClipStrip.tsx', maxCurrentHits: 12 },
  { path: 'src/components/panels/color-workspace/ColorWorkspaceTopBar.tsx', maxCurrentHits: 2 },
  { path: 'src/components/panels/media/panel/useMediaPanelTouchTimelineDrag.ts', maxCurrentHits: 2 },
  { path: 'src/components/panels/media/panel/useMediaPanelTrackingAssets.ts', maxCurrentHits: 6 },
  { path: 'src/components/panels/media/TrackingAssetActions.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/DatamoshBakeSection.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/surfaceTracking/DenseTerrainControls.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/surfaceTracking/LegacySurfaceTrackingTab.tsx', maxCurrentHits: 5 },
  { path: 'src/components/panels/properties/surfaceTracking/SurfaceTrackingTab.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/surfaceTracking/TerrainAttachmentControls.tsx', maxCurrentHits: 6 },
  { path: 'src/components/panels/properties/surfaceTracking/TerrainTrackingControls.tsx', maxCurrentHits: 1 },
  { path: 'src/components/panels/properties/surfaceTracking/TrackingAttachPicker.tsx', maxCurrentHits: 3 },
  { path: 'src/components/panels/properties/surfaceTracking/TrackingConnectionControls.tsx', maxCurrentHits: 11 },
  { path: 'src/components/panels/properties/surfaceTracking/useTrackingAssetActions.ts', maxCurrentHits: 11 },
  { path: 'src/components/panels/properties/surfaceTracking/useTrackingWorkspace.ts', maxCurrentHits: 8 },
  { path: 'src/components/preview/PreviewFpsTouchControls.tsx', maxCurrentHits: 2 },
  { path: 'src/components/preview/tracking/TrackingPreviewOverlay.tsx', maxCurrentHits: 1 },
  { path: 'src/components/preview/useMaskBoundsResize.ts', maxCurrentHits: 1 },
  { path: 'src/components/preview/usePreviewMouseRouting.ts', maxCurrentHits: 3 },
  { path: 'src/components/preview/usePreviewSceneNavigation.ts', maxCurrentHits: 1 },
  { path: 'src/components/preview/usePreview3DMediaDrop.ts', maxCurrentHits: 10 },
  { path: 'src/components/timeline/ClipOriginContextMenuItem.tsx', maxCurrentHits: 1 },
  { path: 'src/components/timeline/components/TimelineSectionHeaderRow.tsx', maxCurrentHits: 5 },
  { path: 'src/components/timeline/hooks/useRulerAnnotations.ts', maxCurrentHits: 3 },
  { path: 'src/components/timeline/utils/clipDragKeyframeDisclosure.ts', maxCurrentHits: 2 },
  { path: 'src/services/colorGrades/remoteColorGradeCommands.ts', maxCurrentHits: 9 },
  { path: 'src/services/liveStream/localRecorder.ts', maxCurrentHits: 1 },
  { path: 'src/services/liveStream/streamSession.ts', maxCurrentHits: 5 },
  { path: 'src/services/liveStream/__tests__/streamStore.test.ts', maxCurrentHits: 18 },
  { path: 'src/services/layerBuilder/audioTrackCompositionPlaybackMixdowns.ts', maxCurrentHits: 1 },
  { path: 'src/services/photogrammetry/cameraSolveTimelineOutputs.ts', maxCurrentHits: 15 },
  { path: 'src/services/photogrammetry/placeSplatOnTimeline.ts', maxCurrentHits: 6 },
  { path: 'src/services/planarTracking/createTrackingScene.ts', maxCurrentHits: 5 },
  { path: 'src/services/planarTracking/editableFootstepPrototype.ts', maxCurrentHits: 2 },
  { path: 'src/services/planarTracking/editableTerrainSequence.ts', maxCurrentHits: 4 },
  { path: 'src/services/planarTracking/surfaceTrackEditing.ts', maxCurrentHits: 3 },
  { path: 'src/services/planarTracking/terrainLayerBindings.ts', maxCurrentHits: 1 },
  { path: 'src/services/planarTracking/trackingAssets.ts', maxCurrentHits: 7 },
  { path: 'src/services/planarTracking/trackingBinding.ts', maxCurrentHits: 1 },
  { path: 'src/stores/slotGridPanelStore.ts', maxCurrentHits: 1 },
  { path: 'src/stores/streamStore.ts', maxCurrentHits: 1 },
  { path: 'src/stores/trackingStore.ts', maxCurrentHits: 1 },
  { path: 'src/stores/timeline/editOperations/activeCompositionFrameRate.ts', maxCurrentHits: 1 },
] as const;
