import type { FieldClass } from './fieldOwnership';
export interface ProjectWriterClassification {
  source: string;
  storage: string;
  class: FieldClass;
  codec: string;
  artifactDependencies: string;
  restoreOwner: string;
  legacyPolicy: string;
}
/** Source-level inventory: every independent writer needs cutover, not only ProjectFile. */
export const PROJECT_WRITER_INVENTORY: readonly ProjectWriterClassification[] = [
  { source: 'services/project/projectSave.ts', storage: 'project.json / .msproj', class: 'mixed', codec: 'encodeProjectDomains', artifactDependencies: 'all domain manifests and original source versions', restoreOwner: 'project lifecycle + domain restore barrier', legacyPolicy: 'pure source-bound readers; source never rewritten' },
  { source: 'services/project/core/ProjectCoreService.ts', storage: 'FSA project package + root', class: 'mixed', codec: 'repository lifecycle', artifactDependencies: 'full project closure', restoreOwner: 'project lifecycle', legacyPolicy: 'do not invoke loadProject as importer' },
  { source: 'services/project/core/NativeProjectCoreService.ts', storage: 'native project package + root', class: 'mixed', codec: 'repository lifecycle', artifactDependencies: 'full project closure', restoreOwner: 'project lifecycle', legacyPolicy: 'pure native source reads; native writer requires negotiated lease' },
  { source: 'services/project/domains/TranscriptService.ts', storage: 'Transcripts/{mediaId}.json', class: 'content', codec: 'transcript aggregate + source identity', artifactDependencies: 'transcript manifest, provider provenance, source version', restoreOwner: 'transcript/media hydration', legacyPolicy: 'preserve words + ranges + hybrid provenance; path alone does not identify source version' },
  { source: 'services/project/domains/AnalysisService.ts', storage: 'Analysis/{mediaId}.json and source annotations', class: 'content', codec: 'analysis aggregate', artifactDependencies: 'range frames, face analysis, scene-description manifests, source version', restoreOwner: 'analysis/media hydration', legacyPolicy: 'strip cache createdAt; retain semantic frame timestamps; preserve contradictory versions as evidence' },
  { source: 'services/documents/documentArtifacts.ts', storage: 'Documents/versioned document JSON + originals', class: 'content', codec: 'document / documentManifest', artifactDependencies: 'document digest and original digest; attachments', restoreOwner: 'documents store', legacyPolicy: 'structure distinguishes inline-v2 from manifest-v2; originals are required archive dependencies' },
  { source: 'services/project/domains/RawMediaService.ts', storage: 'Raw original media + downloads', class: 'content', codec: 'source version + resolver binding', artifactDependencies: 'full original SHA256 + length; fast fingerprint is unverified', restoreOwner: 'media source runtime', legacyPolicy: 'read only; link originals or copy explicitly to independent destination' },
  { source: 'services/project/domains/ArtifactService.ts', storage: 'project Artifacts + global IndexedDB', class: 'content', codec: 'immutable artifact manifest', artifactDependencies: 'blob hash separate from manifest version', restoreOwner: 'artifact owner', legacyPolicy: 'never use mutable old manifest ID as a historical immutable record' },
  { source: 'artifacts/ArtifactStore.ts', storage: 'artifact adapter + manifest index', class: 'content', codec: 'immutable artifact manifest', artifactDependencies: 'blob bytes and transitive source refs', restoreOwner: 'artifact owner', legacyPolicy: 'mutable metadata/sourceRefs under same blob ID must be versioned independently' },
  { source: 'artifacts/projectDBStorageAdapter.ts', storage: 'global IndexedDB artifact blobs/manifests', class: 'mixed', codec: 'immutable artifact + retention roots', artifactDependencies: 'content-owned artifacts for every project and branch', restoreOwner: 'artifact owner', legacyPolicy: 'global cleanup must protect foreign repositories; cache-only artifacts may be rebuilt' },
  { source: 'artifacts/fileSystemStorageAdapter.ts', storage: 'Artifacts/{hash}/artifact.bin + manifest.json', class: 'content', codec: 'immutable artifact manifest', artifactDependencies: 'blob hash/length and pinned manifest', restoreOwner: 'artifact owner', legacyPolicy: 'read old mutable manifests without rewriting source' },
  { source: 'services/project/domains/CacheService.ts', storage: 'Cache/Thumbnails, Waveforms, Splats', class: 'cache', codec: 'local media cache binding', artifactDependencies: 'full verified source identity; cache reconstructed on miss', restoreOwner: 'media/cache runtime', legacyPolicy: 'never create a content revision for thumbnail/waveform/cache timestamp hydration' },
  { source: 'services/project/domains/ProxyStorageService.ts', storage: 'Proxies/{mediaId}, proxy.mp4, audio proxy, packed JPEG indexes', class: 'cache', codec: 'local proxy resolver', artifactDependencies: 'source identity + reproducible proxy settings', restoreOwner: 'proxy runtime', legacyPolicy: 'proxies are optional if original remains; source unavailable requires explicit artifact classification' },
  { source: 'services/audio/projectAudioState.ts', storage: 'ProjectFile.audio index', class: 'derived', codec: 'composition master / audio artifacts', artifactDependencies: 'analysis and derived-asset manifests', restoreOwner: 'composition audio owner', legacyPolicy: 'active composition does not define a project-wide canonical master' },
  { source: 'services/audio/sourceWaveformPersistence.ts', storage: 'waveform artifact manifest/payload', class: 'cache', codec: 'audio analysis manifest', artifactDependencies: 'source identity + clip audio state hash', restoreOwner: 'audio waveform runtime', legacyPolicy: 'promote only referenced analysis versions to required content artifacts' },
  { source: 'services/audio/waveformPyramid/pyramidPersistence.ts', storage: 'waveform pyramid artifact store', class: 'cache', codec: 'audio analysis manifest', artifactDependencies: 'manifest and bounded bucket blobs', restoreOwner: 'audio waveform runtime', legacyPolicy: 'job events journal; previews reconstructible' },
  { source: 'services/audio/intelligence/audioIntelligencePersistence.ts', storage: 'voice activity artifact store', class: 'content', codec: 'audio analysis binding', artifactDependencies: 'voice activity manifest + source version', restoreOwner: 'audio intelligence runtime', legacyPolicy: 'job status journal; selected analysis binding canonical' },
  { source: 'services/audio/intelligence/AudioIntelligenceRuntime.ts', storage: 'artifact store + job state', class: 'mixed', codec: 'audio binding + audio-job journal', artifactDependencies: 'analysis payloads and model/source identity', restoreOwner: 'audio runtime; jobs not restarted by checkout', legacyPolicy: 'separate result binding from execution events' },
  { source: 'services/audio/recording/recoveryPersistence.ts', storage: 'OPFS recording recovery + localStorage recovery entries', class: 'journal', codec: 'recording recovery journal', artifactDependencies: 'recorded chunks promoted to source versions after completion', restoreOwner: 'recording recovery owner', legacyPolicy: 'unfinished captures stay local recovery evidence; never resume implicitly' },
  { source: 'services/audio/audioEqPresetStorage.ts', storage: 'localStorage user presets/favorite IDs', class: 'workspace', codec: 'local user preferences', artifactDependencies: 'none; applied effect values canonical', restoreOwner: 'audio preset UI', legacyPolicy: 'global presets remain outside transportable project; applied stack preserved' },
  { source: 'services/landmarkTracking/landmarkSidecar.ts', storage: 'Cache Storage sidecar indexed by clipId', class: 'content', codec: 'landmark source result manifest', artifactDependencies: 'project/owner/source version + landmark bytes', restoreOwner: 'tracking runtime', legacyPolicy: 'unbound clip-only cache match remains ambiguous evidence, never auto-import as historical content' },
  { source: 'services/landmarkTracking/modelCatalog.ts', storage: 'Cache Storage model binaries', class: 'cache', codec: 'local tracking model cache', artifactDependencies: 'model version/integrity; not project results', restoreOwner: 'landmark model runtime', legacyPolicy: 'model execution cache is not content' },
  { source: 'stores/trackingStore.ts', storage: 'ProjectFile.trackingAssets + snapshot tracking', class: 'content', codec: 'trackingAssets aggregate', artifactDependencies: 'planar/terrain/source-space result manifests', restoreOwner: 'tracking store + runtime rebind', legacyPolicy: 'preserve normalized source-space assets; forbid runtime mesh/GPU handles' },
  { source: 'services/agentTimeline/storage/projectAgentTimelineStorage.ts', storage: 'Analysis manifest pointer + localStorage fallback', class: 'journal', codec: 'agent-timeline journal', artifactDependencies: 'manifest/index/shard artifact refs + source identity', restoreOwner: 'AgentTimelineArtifactStorage', legacyPolicy: 'pointer source-bound; preserve evidence without replaying tools/provider calls' },
  { source: 'services/agentTimeline/storage/AgentTimelineArtifactStorage.ts', storage: 'artifact manifests + shard indexes/payloads', class: 'journal', codec: 'agent-timeline journal', artifactDependencies: 'ordered shard closure + normalized source identity', restoreOwner: 'AgentTimelineArtifactStorage', legacyPolicy: 'rehydrating a generation must not rewrite pointer or start work' },
  { source: 'services/flashboard/FlashBoardChatRunAudit.ts', storage: 'chat run audit files via project storage', class: 'journal', codec: 'chat/audit journal', artifactDependencies: 'ordered calls/results, prompt/audit provenance', restoreOwner: 'FlashBoard chat continuity', legacyPolicy: 'history checkout does not erase conversation or rerun external work' },
  { source: 'stores/flashboardStore', storage: 'ProjectFile.flashboard + hosted reload checkpoint', class: 'mixed', codec: 'flashboard board + conversation/generation journal + composer workspace', artifactDependencies: 'generated media source versions, result bindings, generation provenance', restoreOwner: 'FlashBoard board/chat runtime', legacyPolicy: 'execution states remain journal; only authored board/result bindings canonical' },
  { source: 'stores/documentsStore.ts', storage: 'documents project state + document artifacts', class: 'mixed', codec: 'document aggregate + document workspace', artifactDependencies: 'originals/attachments and inline payloads', restoreOwner: 'documents store', legacyPolicy: 'restore barrier independent from history snapshot setter' },
  { source: 'stores/exportStore.ts', storage: 'ProjectUIState.exportState', class: 'mixed', codec: 'export definitions + export workspace + execution journal', artifactDependencies: 'selected media/source versions for definitions', restoreOwner: 'export definitions owner', legacyPolicy: 'opening/checking out never starts an export' },
  { source: 'stores/midiStore.ts', storage: 'ProjectUIState.midi + local device state', class: 'mixed', codec: 'semantic MIDI bindings + local MIDI workspace', artifactDependencies: 'track instruments/notes/CC within track/clip aggregates', restoreOwner: 'MIDI runtime', legacyPolicy: 'isEnabled/device connection stays local; semantic binding values canonical' },
  { source: 'stores/mediaStore', storage: 'ProjectFile media/generated/signal items + handle IndexedDB', class: 'mixed', codec: 'media/generated/source/resolver aggregates', artifactDependencies: 'sources, 3D sequences, generated results, signal manifests', restoreOwner: 'media runtime rehydration', legacyPolicy: 'handles never enter records; canvas/decoder/DOM/GPU regenerated' },
  { source: 'stores/historyStore/historyProjectState.ts', storage: 'ProjectUIState.history', class: 'journal', codec: 'importRawLegacyHistory', artifactDependencies: 'raw original snapshots/provenance', restoreOwner: 'legacy import coordinator', legacyPolicy: 'all roots/branches retained; no historic composition context fabricated' },
] as const;
