import type { TransitionDefinition } from '../types';

// Deterministic warm edge leak overlay plus a soft dissolve.
export const lightLeak: TransitionDefinition = {
  id: 'light-leak',
  name: 'Light Leak',
  category: 'light',
  defaultDuration: 1.25,
  minDuration: 0.1,
  maxDuration: 5,
  description: 'A warm analog edge leak washes across the cut',
  params: {
    color: {
      type: 'color',
      label: 'Color',
      defaultValue: '#ffb36a',
    },
  },
  recipe: [
    {
      kind: 'opacity',
      target: 'outgoing',
      from: 1,
      to: 0,
      startProgress: 0.18,
      endProgress: 0.88,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'incoming',
      from: 0,
      to: 1,
      startProgress: 0.12,
      endProgress: 0.82,
      curve: 'ease-out',
    },
    {
      kind: 'overlay',
      overlay: 'light-leak',
      color: '#ffb36a',
      colorParam: 'color',
      blendMode: 'screen',
      opacity: { from: 0, to: 0.86 },
      centerX: { from: -0.2, to: 0.42 },
      width: 0.44,
      softness: 0.42,
      angle: 0.12,
      startProgress: 0,
      endProgress: 0.58,
      curve: 'ease-out',
    },
    {
      kind: 'overlay',
      overlay: 'light-leak',
      color: '#ffb36a',
      colorParam: 'color',
      blendMode: 'screen',
      opacity: { from: 0.62, to: 0 },
      centerX: { from: 0.28, to: 1.08 },
      width: 0.52,
      softness: 0.48,
      angle: -0.08,
      startProgress: 0.44,
      endProgress: 1,
      curve: 'ease-in',
    },
  ],
};
