import type { BoundOperatorNode, EffectOperatorGraph, OperatorEdge } from '../../types/operatorGraph';

type Ref = { node: string; port: string };
class B {
  nodes: BoundOperatorNode[]=[]; edges: OperatorEdge[]=[]; layout: EffectOperatorGraph['layout']={};
  node(id:string,operator:string,port='value',bindings:BoundOperatorNode['bindings']={},constants?:BoundOperatorNode['constants']):Ref { this.nodes.push({id,operator,operatorVersion:1,bindings,...(constants?{constants}:{})}); this.layout[id]={x:(this.nodes.length%12)*280,y:Math.floor(this.nodes.length/12)*210}; return {node:id,port}; }
  n(id:string,value:number){return this.node(id,'values.number','value',{}, {value});}
  e(from:Ref,to:Ref,input:string){this.edges.push({id:`${from.node}-${to.node}-${input}`,from:from.node,output:from.port,to:to.node,input});}
  u(id:string,op:string,v:Ref,input='value'){const o=this.node(id,op);this.e(v,o,input);return o;}
  b(id:string,op:string,a:Ref,b:Ref){const o=this.node(id,op);this.e(a,o,'a');this.e(b,o,'b');return o;}
  v2(id:string,x:Ref,y:Ref){const o=this.node(id,'vector.combine.vec2');this.e(x,o,'x');this.e(y,o,'y');return o;}
}

function noise2d(g:B,id:string,p:Ref,z:Ref,o:Ref,two:Ref,three:Ref){
  const i=g.u(`${id}-i`,'math.floor.vec2',p),f=g.u(`${id}-f`,'math.fract.vec2',p),f2=g.b(`${id}-f2`,'math.multiply.vec2',f,f);
  const twice=g.node(`${id}-twice`,'math.multiply.vec2-scalar');g.e(f,twice,'a');g.e(two,twice,'b');
  const three2=g.u(`${id}-three2`,'convert.scalar-to-vec2',three),fade=g.b(`${id}-fade`,'math.multiply.vec2',f2,g.b(`${id}-fade-base`,'math.subtract.vec2',three2,twice));
  const fs=g.node(`${id}-fade-split`,'vector.split.vec2','x');g.e(fade,fs,'value');
  const point=(suffix:string,x:Ref,y:Ref)=>g.b(`${id}-${suffix}`,'math.add.vec2',i,g.v2(`${id}-${suffix}-offset`,x,y));
  const hash=(suffix:string,v:Ref)=>g.u(`${id}-h${suffix}`,'noise.hash2d.vec2',v);
  const h00=hash('00',point('p00',z,z)),h10=hash('10',point('p10',o,z)),h01=hash('01',point('p01',z,o)),h11=hash('11',point('p11',o,o));
  const mix=(suffix:string,a:Ref,b:Ref,t:Ref)=>{const out=g.node(`${id}-${suffix}`,'math.mix.scalar');g.e(a,out,'a');g.e(b,out,'b');g.e(t,out,'t');return out;};
  return mix('result',mix('row0',h00,h10,{node:fs.node,port:'x'}),mix('row1',h01,h11,{node:fs.node,port:'x'}),{node:fs.node,port:'y'});
}

/** Exact four-octave expansion of the legacy feedback watercolor shader. */
export function createDefaultAcuarelaGraph():EffectOperatorGraph {
  const g=new B(),frame=g.node('frame','image.frame','image'),feedback=g.node('feedback','image.frame-history','image'),uv=g.node('uv','image.normalized-uv','uv');
  const bind=(id:string)=>g.node(id,id==='reset'?'values.boolean':'values.number','value',{value:id});
  const opacity=bind('opacity'),gain=bind('gain'),speed=bind('speed'),detail=bind('detail'),strength=bind('strength'),density=bind('density'),gainX=bind('gainX'),gainY=bind('gainY');
  const time=g.node('time','image.timeline-time'),z=g.n('zero',0),one=g.n('one',1),two=g.n('two',2),three=g.n('three',3),tiny=g.n('tiny',.001);
  const safeDensity=g.node('safe-density','math.max.scalar');g.e(density,safeDensity,'a');g.e(tiny,safeDensity,'b'); const safeDetail=g.node('safe-detail','math.max.scalar');g.e(detail,safeDetail,'a');g.e(tiny,safeDetail,'b');
  const safeSpeed=g.node('safe-speed','math.max.scalar');g.e(speed,safeSpeed,'a');g.e(z,safeSpeed,'b');
  const driven=g.b('driven-time','math.multiply.scalar',g.b('time-speed','math.multiply.scalar',time,safeSpeed),g.n('time-scale',.75));
  const densityUv=g.node('density-uv','math.multiply.vec2-scalar');g.e(uv,densityUv,'a');g.e(safeDensity,densityUv,'b');
  const noiseUv=g.node('noise-uv','math.multiply.vec2-scalar');g.e(densityUv,noiseUv,'a');g.e(safeDetail,noiseUv,'b');
  let sum=g.u('sum-zero','convert.scalar-to-vec2',z),normalizer=z;
  const frequencies=[1,2,4,8],amplitudeRatio=g.n('amplitude-ratio',.53);let amplitude=g.n('amplitude-0',.5);
  frequencies.forEach((frequency,index)=>{ const f=g.n(`frequency-${index}`,frequency),amp=amplitude; const p=g.node(`octave-${index}-p`,'math.multiply.vec2-scalar');g.e(noiseUv,p,'a');g.e(f,p,'b');
    const octaveTime=g.b(`octave-${index}-time`,'math.add.scalar',driven,g.n(`octave-${index}-time-offset`,index*13.37));
    const shifted=(id:string,x:number,y:number)=>g.b(id,'math.add.vec2',p,g.v2(`${id}-offset`,g.b(`${id}-x`,'math.multiply.scalar',octaveTime,g.n(`${id}-xr`,x)),g.b(`${id}-y`,'math.multiply.scalar',octaveTime,g.n(`${id}-yr`,y))));
    const n1=noise2d(g,`octave-${index}-n1`,shifted(`octave-${index}-p1`,.19,.31),z,one,two,three);
    const p1173=g.node(`octave-${index}-p1173`,'math.multiply.vec2-scalar');g.e(p,p1173,'a');g.e(g.n(`octave-${index}-1173`,1.173),p1173,'b');
    const n2Offset=g.v2(`octave-${index}-n2-offset`,g.b(`octave-${index}-n2-x`,'math.subtract.scalar',g.n(`octave-${index}-1917`,19.17),g.b(`octave-${index}-t27`,'math.multiply.scalar',octaveTime,g.n(`octave-${index}-027`,.27))),g.b(`octave-${index}-n2-y`,'math.add.scalar',g.n(`octave-${index}-731`,7.31),g.b(`octave-${index}-t16`,'math.multiply.scalar',octaveTime,g.n(`octave-${index}-016`,.16))));
    const n2=noise2d(g,`octave-${index}-n2`,g.b(`octave-${index}-n2-p`,'math.add.vec2',p1173,n2Offset),z,one,two,three),nv=g.v2(`octave-${index}-noise`,n1,n2),two2=g.u(`octave-${index}-two2`,'convert.scalar-to-vec2',two),one2=g.u(`octave-${index}-one2`,'convert.scalar-to-vec2',one);
    const centered=g.b(`octave-${index}-centered`,'math.subtract.vec2',g.b(`octave-${index}-twice`,'math.multiply.vec2',nv,two2),one2),weighted=g.node(`octave-${index}-weighted`,'math.multiply.vec2-scalar');g.e(centered,weighted,'a');g.e(amp,weighted,'b');sum=g.b(`sum-${index}`,'math.add.vec2',sum,weighted);normalizer=g.b(`normalizer-${index}`,'math.add.scalar',normalizer,amp);if(index<frequencies.length-1)amplitude=g.b(`amplitude-${index+1}`,'math.multiply.scalar',amplitude,amplitudeRatio); });
  const norm2=g.u('normalizer-vec2','convert.scalar-to-vec2',normalizer),offsetBase=g.b('offset-base','math.divide-ieee.vec2',sum,norm2),negativeGainY=g.b('negative-gain-y','math.multiply.scalar',gainY,g.n('negative-one',-1));
  const gainVector=g.v2('gain-vector',gainX,negativeGainY),gainStrength=g.node('gain-strength','math.multiply.vec2-scalar');g.e(gainVector,gainStrength,'a');g.e(strength,gainStrength,'b');
  const offsetGainScale=g.node('offset-gain-scale','math.multiply.vec2-scalar');g.e(gainStrength,offsetGainScale,'a');g.e(g.n('offset-scale',.024),offsetGainScale,'b');const offset=g.b('offset','math.multiply.vec2',offsetBase,offsetGainScale);
  const warped=g.b('warped-uv','math.add.vec2',uv,offset),zero2=g.u('zero2','convert.scalar-to-vec2',z),one2=g.u('one2','convert.scalar-to-vec2',one),clampUv=(id:string,v:Ref)=>{const o=g.node(id,'math.clamp.vec2');g.e(v,o,'value');g.e(zero2,o,'min');g.e(one2,o,'max');return o;},sample=(id:string,image:Ref,coords:Ref)=>{const o=g.node(id,'image.sample','image');g.e(image,o,'image');g.e(coords,o,'uv');return o;};
  const feedbackUv=clampUv('feedback-uv',warped),feedbackSample=sample('feedback-sample',feedback,feedbackUv),wet=sample('wet-source',frame,feedbackUv),source=sample('source',frame,uv);
  const smear=(id:string,factor:number,subtract=false)=>{const scaled=g.node(`${id}-scaled`,'math.multiply.vec2-scalar');g.e(offset,scaled,'a');g.e(g.n(`${id}-factor`,factor),scaled,'b');return sample(id,frame,clampUv(`${id}-uv`,g.b(`${id}-coords`,subtract?'math.subtract.vec2':'math.add.vec2',uv,scaled)));};
  const a=smear('smear-a',.45),b=smear('smear-b',.65,true),os=g.node('offset-split','vector.split.vec2','x');g.e(offset,os,'value');const perpendicular=g.v2('perpendicular',g.b('negative-y','math.multiply.scalar',{node:os.node,port:'y'},g.n('minus-one-b',-1)),{node:os.node,port:'x'}),perpScaled=g.node('perp-scaled','math.multiply.vec2-scalar');g.e(perpendicular,perpScaled,'a');g.e(g.n('perp-half',.5),perpScaled,'b');const c=sample('smear-c',frame,clampUv('smear-c-uv',g.b('smear-c-coords','math.add.vec2',uv,perpScaled)));
  const split=(id:string,v:Ref)=>{const o=g.node(`${id}-split`,'vector.split.rgba','rgb');g.e(v,o,'image');return o;},alpha=(id:string,v:Ref)=>{const rgba=g.node(`${id}-vec4`,'convert.image-to-vec4');g.e(v,rgba,'image');const parts=g.node(`${id}-components`,'vector.split.vec4','x');g.e(rgba,parts,'value');return {node:parts.node,port:'w'};},ss=split('source',source),ws=split('wet',wet),as=split('a',a),bs=split('b',b),cs=split('c',c),fs=split('feedback',feedbackSample),sourceAlpha=alpha('source-alpha',source),feedbackAlphaValue=alpha('feedback-alpha',feedbackSample);
  const feedbackMaskEdge=(()=>{const us=g.node('warped-split','vector.split.vec2','x');g.e(warped,us,'value');const xMin=g.node('edge-x','math.min.scalar');g.e({node:us.node,port:'x'},xMin,'a');g.e(g.b('one-minus-x','math.subtract.scalar',one,{node:us.node,port:'x'}),xMin,'b');const yMin=g.node('edge-y','math.min.scalar');g.e({node:us.node,port:'y'},yMin,'a');g.e(g.b('one-minus-y','math.subtract.scalar',one,{node:us.node,port:'y'}),yMin,'b');const edge=g.node('edge-min','math.min.scalar');g.e(xMin,edge,'a');g.e(yMin,edge,'b');const mask=g.node('edge-mask','math.smoothstep.scalar');g.e(g.n('edge-low',-.005),mask,'edge0');g.e(g.n('edge-high',.025),mask,'edge1');g.e(edge,mask,'value');return mask;})();
  const feedbackRgb=g.node('feedback-masked','math.multiply.rgb-scalar');g.e({node:fs.node,port:'rgb'},feedbackRgb,'a');g.e(feedbackMaskEdge,feedbackRgb,'b');const feedbackAlpha=g.b('feedback-alpha-mask','math.multiply.scalar',feedbackAlphaValue,feedbackMaskEdge);
  const gainValue=g.b('gain-value','math.multiply.scalar',(()=>{const o=g.node('safe-gain','math.max.scalar');g.e(gain,o,'a');g.e(z,o,'b');return o;})(),g.n('gain-scale',.35)); const gainRgb=g.node('gain-rgb','convert.scalar-to-rgb','rgb');g.e(gainValue,gainRgb,'value');const sourceAlphaGain=g.node('source-alpha-gain','math.multiply.rgb-scalar');g.e(gainRgb,sourceAlphaGain,'a');g.e(sourceAlpha,sourceAlphaGain,'b');const lifted=g.b('lifted-add','math.add.rgb',{node:ss.node,port:'rgb'},sourceAlphaGain),liftedClamp=g.node('lifted','math.clamp.rgb-scalar');g.e(lifted,liftedClamp,'value');g.e(z,liftedClamp,'min');g.e(one,liftedClamp,'max');
  const quarter=g.n('quarter',.25),washSum=g.b('wash-1','math.add.rgb',{node:ws.node,port:'rgb'},{node:as.node,port:'rgb'}),washSum2=g.b('wash-2','math.add.rgb',washSum,{node:bs.node,port:'rgb'}),washSum3=g.b('wash-3','math.add.rgb',washSum2,{node:cs.node,port:'rgb'}),wash=g.node('wash','math.multiply.rgb-scalar');g.e(washSum3,wash,'a');g.e(quarter,wash,'b');
  const mixRgb=(id:string,x:Ref,y:Ref,t:Ref)=>{const o=g.node(id,'math.mix.rgb');g.e(x,o,'a');g.e(y,o,'b');g.e(t,o,'t');return o;},warpRaw=g.b('warp-mix-raw','math.multiply.scalar',strength,g.n('warp-factor',.92)),warpMix=g.node('warp-mix','math.clamp.scalar');g.e(warpRaw,warpMix,'value');g.e(z,warpMix,'min');g.e(g.n('warp-max',.92),warpMix,'max');const current=mixRgb('warped-current',liftedClamp,wash,warpMix);
  const decay=g.n('feedback-decay',.98),delayed=g.node('delayed-scaled','math.multiply.rgb-scalar');g.e(feedbackRgb,delayed,'a');g.e(decay,delayed,'b');const delayedClamp=g.node('delayed','math.clamp.rgb-scalar');g.e(delayed,delayedClamp,'value');g.e(z,delayedClamp,'min');g.e(one,delayedClamp,'max');
  const feedbackMixRaw=g.b('feedback-mix-raw','math.add.scalar',g.b('strength-memory','math.multiply.scalar',strength,g.n('strength-memory-factor',.1)),g.b('opacity-memory','math.multiply.scalar',opacity,g.n('opacity-memory-factor',.04))),feedbackMix=g.node('feedback-mix','math.clamp.scalar');g.e(feedbackMixRaw,feedbackMix,'value');g.e(z,feedbackMix,'min');g.e(g.n('feedback-mix-max',.14),feedbackMix,'max');const memory=mixRgb('memory',current,delayedClamp,feedbackMix);
  const limitOffset=g.b('limit-offset','math.add.scalar',g.n('limit-base',.1),g.b('gain-double','math.multiply.scalar',gainValue,two)),limitRgb=g.node('limit-rgb','convert.scalar-to-rgb','rgb');g.e(limitOffset,limitRgb,'value');const paperBase=g.node('paper-base','math.max.rgb');g.e({node:ss.node,port:'rgb'},paperBase,'a');g.e(wash,paperBase,'b');const paper=g.b('paper-limit','math.add.rgb',paperBase,limitRgb);
  const componentMin=(id:string,x:Ref,y:Ref)=>{const xs=g.node(`${id}-xs`,'convert.rgb-to-vec3');g.e(x,xs,'rgb');const ys=g.node(`${id}-ys`,'convert.rgb-to-vec3');g.e(y,ys,'rgb');const xa=g.node(`${id}-xa`,'vector.split.vec3','x');g.e(xs,xa,'value');const ya=g.node(`${id}-ya`,'vector.split.vec3','x');g.e(ys,ya,'value');const out=g.node(`${id}-v`,'vector.combine.vec3');for(const p of ['x','y','z']){const m=g.node(`${id}-${p}`,'math.min.scalar');g.e({node:xa.node,port:p},m,'a');g.e({node:ya.node,port:p},m,'b');g.e(m,out,p);}const rgb=g.node(id,'convert.vec3-to-rgb','rgb');g.e(out,rgb,'value');return rgb;};const waterRgb=componentMin('water-rgb',memory,paper);
  const decayedAlpha=g.b('decayed-alpha','math.multiply.scalar',feedbackAlpha,decay),alphaMax=g.node('alpha-max','math.max.scalar');g.e(sourceAlpha,alphaMax,'a');g.e(decayedAlpha,alphaMax,'b');const waterAlpha=g.node('water-alpha','math.clamp.scalar');g.e(alphaMax,waterAlpha,'value');g.e(z,waterAlpha,'min');g.e(one,waterAlpha,'max');
  const waterRgbVec=g.node('water-rgb-vec3','convert.rgb-to-vec3');g.e(waterRgb,waterRgbVec,'rgb');const waterParts=g.node('water-rgb-components','vector.split.vec3','x');g.e(waterRgbVec,waterParts,'value');const waterV=g.node('water-vec4','vector.combine.vec4');for(const p of ['x','y','z'])g.e({node:waterParts.node,port:p},waterV,p);g.e(waterAlpha,waterV,'w');const opacityClamp=g.node('opacity-clamp','math.clamp.scalar');g.e(opacity,opacityClamp,'value');g.e(z,opacityClamp,'min');g.e(one,opacityClamp,'max');const sourceV=g.node('source-final-vec4','convert.image-to-vec4');g.e(source,sourceV,'image');const mixed=g.node('mixed','math.mix.vec4');g.e(sourceV,mixed,'a');g.e(waterV,mixed,'b');g.e(opacityClamp,mixed,'t');const image=g.node('mixed-image','convert.vec4-to-image','image');g.e(mixed,image,'value');const output=g.node('output','image.output','');g.e(image,output,'image');
  return {version:1,schemaVersion:1,domain:'image',nodes:g.nodes,edges:g.edges,layout:g.layout};
}
