import type { BoundOperatorNode, EffectOperatorGraph, OperatorEdge } from '../../types/operatorGraph';
type Ref = { node: string; port: string };
class Builder { nodes: BoundOperatorNode[] = []; edges: OperatorEdge[] = []; layout: EffectOperatorGraph['layout'] = {};
  node(id: string, operator: string, port = 'value', bindings: BoundOperatorNode['bindings'] = {}, constants?: BoundOperatorNode['constants']): Ref { this.nodes.push({ id, operator, operatorVersion: 1, bindings, ...(constants ? { constants } : {}) }); this.layout[id] = { x: (this.nodes.length % 9) * 340, y: Math.floor(this.nodes.length / 9) * 360 }; return { node: id, port }; }
  number(id: string, value: number) { return this.node(id, 'values.number', 'value', {}, { value }); } edge(from: Ref, to: Ref, input: string) { this.edges.push({ id: `${from.node}-${from.port}-${to.node}-${input}`, from: from.node, output: from.port, to: to.node, input }); }
  unary(id: string, operator: string, value: Ref) { const out = this.node(id, operator); this.edge(value, out, 'value'); return out; } binary(id: string, operator: string, a: Ref, b: Ref) { const out = this.node(id, operator); this.edge(a, out, 'a'); this.edge(b, out, 'b'); return out; } }
export function createDefaultCrossStitchGraph(): EffectOperatorGraph {
  const g = new Builder(), frame = g.node('frame', 'image.frame', 'image'), uv = g.node('uv', 'image.normalized-uv', 'uv'), resolution = g.node('resolution', 'image.resolution');
  const scale = g.node('scale', 'values.number', 'value', { value: 'scale' }), amount = g.node('amount', 'values.number', 'value', { value: 'amount' }), colorA = g.node('color-a', 'values.color', 'value', { value: 'colorA' }), colorB = g.node('color-b', 'values.color', 'value', { value: 'colorB' });
  const one = g.number('one', 1), half = g.number('half', .5), three = g.number('three', 3), safeScale = g.binary('safe-scale', 'math.max.scalar', scale, three), scale2 = g.unary('scale-vec2', 'convert.scalar-to-vec2', safeScale), half2 = g.unary('half-vec2', 'convert.scalar-to-vec2', half);
  const cells = g.binary('cells', 'math.divide-ieee.vec2', g.binary('pixels', 'math.multiply.vec2', uv, resolution), scale2), cell = g.binary('cell', 'math.subtract.vec2', g.unary('cell-fract', 'math.fract.vec2', cells), half2), split = g.node('cell-split', 'vector.split.vec2'); g.edge(cell, split, 'value'); const x = { node: split.node, port: 'x' }, y = { node: split.node, port: 'y' };
  const lineA = g.unary('line-a', 'math.abs.scalar', g.binary('x-minus-y', 'math.subtract.scalar', x, y)), lineB = g.unary('line-b', 'math.abs.scalar', g.binary('x-plus-y', 'math.add.scalar', x, y)), line = g.binary('line', 'math.min.scalar', lineA, lineB);
  const edgeNode = g.node('line-edge', 'math.smoothstep.scalar'); g.edge(g.number('line-low', .04), edgeNode, 'edge0'); g.edge(g.number('line-high', .1), edgeNode, 'edge1'); g.edge(line, edgeNode, 'value'); const inverseEdge = g.binary('inverse-edge', 'math.subtract.scalar', one, edgeNode);
  const inside = g.node('inside', 'math.step.scalar'); g.edge(g.unary('cell-length', 'vector.length.vec2', cell), inside, 'edge'); g.edge(g.number('inside-limit', .62), inside, 'value'); const stitch = g.binary('stitch', 'math.multiply.scalar', inverseEdge, inside);
  const min2 = g.unary('min-uv', 'convert.scalar-to-vec2', g.number('tiny', .001)), max2 = g.unary('max-uv', 'convert.scalar-to-vec2', g.number('almost', .999)), clamped = g.node('clamped-uv', 'math.clamp.vec2'); g.edge(uv, clamped, 'value'); g.edge(min2, clamped, 'min'); g.edge(max2, clamped, 'max'); const sample = g.node('sample', 'image.sample', 'image'); g.edge(frame, sample, 'image'); g.edge(clamped, sample, 'uv'); const sampleSplit = g.node('sample-split', 'vector.split.rgba', 'rgb'); g.edge(sample, sampleSplit, 'image'); const rgb = { node: sampleSplit.node, port: 'rgb' };
  const aRgb = g.node('color-a-rgb', 'convert.vec4-to-rgb', 'rgb'), bRgb = g.node('color-b-rgb', 'convert.vec4-to-rgb', 'rgb'); g.edge(colorA, aRgb, 'value'); g.edge(colorB, bRgb, 'value'); const colored = g.node('colored', 'math.multiply.rgb'); g.edge(rgb, colored, 'a'); g.edge(aRgb, colored, 'b'); const ink = g.node('ink', 'math.mix.rgb'); g.edge(bRgb, ink, 'a'); g.edge(colored, ink, 'b'); g.edge(stitch, ink, 't'); const mixed = g.node('mixed', 'math.mix.rgb'); g.edge(rgb, mixed, 'a'); g.edge(ink, mixed, 'b'); g.edge(amount, mixed, 't'); const combine = g.node('combine', 'vector.combine.rgba', 'image'); g.edge(mixed, combine, 'rgb'); g.edge({ node: sampleSplit.node, port: 'alpha' }, combine, 'alpha'); const output = g.node('output', 'image.output', ''); g.edge(combine, output, 'image');
  return { version: 1, schemaVersion: 1, domain: 'image', nodes: g.nodes, edges: g.edges, layout: g.layout };
}
