import type { OperatorDefinition, OperatorPort } from '../../types/operatorGraph';

const port = (id: string, type: OperatorPort['type'], label: string, required = false): OperatorPort =>
  ({ id, type, label, required, ...(type === 'image' && required
    ? { contract: { formats: ['decoded-frame', 'analog-decoded-360x288-rgba16f'] } } : {}) });

const imageOperator = (definition: Omit<OperatorDefinition, 'version' | 'invalidates' | 'runtime' | 'state' | 'fusion'>): OperatorDefinition => ({
  ...definition,
  version: 1,
  invalidates: 'appearance',
  runtime: 'builtin',
  state: 'stateless',
  fusion: 'inline',
  adaptivePorts: definition.family?.startsWith('math.') || definition.family === 'vector.split' || definition.family === 'vector.combine',
});

const vectorOperators = ([2, 3, 4] as const).flatMap(size => {
  const type = `vec${size}` as 'vec2' | 'vec3' | 'vec4';
  const components = ['x', 'y', 'z', 'w'].slice(0, size);
  return [
    imageOperator({ id: `vector.split.${type}`, family: 'vector.split', variant: type, label: `Split ${type.toUpperCase()}`, description: `Separates ${size} ordered vector components.`,
      inputs: [port('value', type, 'Value', true)], outputs: components.map(id => port(id, 'number', id.toUpperCase())), parameters: [], addable: true }),
    imageOperator({ id: `vector.combine.${type}`, family: 'vector.combine', variant: type, label: `Combine ${type.toUpperCase()}`, description: `Combines ${size} scalars into one ordered vector.`,
      inputs: components.map(id => port(id, 'number', id.toUpperCase(), true)), outputs: [port('value', type, 'Value')], parameters: [], addable: true }),
  ];
});

/** Operators newly owned by the local image compiler. image.frame and values.number stay canonical registry entries. */
export const IMAGE_OPERATORS: readonly OperatorDefinition[] = [
  imageOperator({ id: 'values.integer', family: 'values.numeric', variant: 'integer', label: 'Value',
    description: 'An integer-valued scalar. Truncates toward zero after animation; keeps the numeric signal compatible with math inputs.',
    inputs: [], outputs: [port('value', 'number', 'Value')],
    parameters: [{ id: 'value', label: 'Value', type: 'number', default: 1, min: -30, max: 30, step: 1, animatable: true }], addable: true }),
  ...vectorOperators,
  imageOperator({ id: 'vector.normalize.vec2', family: 'vector.normalize', variant: 'vec2', label: 'Normalize Vector',
    description: 'Normalizes a nonzero two-component vector; the CPU reference defines a zero vector as zero.',
    inputs: [port('value', 'vec2', 'Value', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [],
    consumers: ['image'], implementation: 'shared', addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'pattern.bayer4.vec2', family: 'pattern.bayer', variant: '4x4', label: 'Bayer 4×4',
    description: 'Returns the normalized threshold from the canonical 4×4 Bayer matrix after flooring and clamping coordinates to nonnegative values.',
    inputs: [port('value', 'vec2', 'Pixel', true)], outputs: [port('value', 'number', 'Threshold')], parameters: [],
    consumers: ['image'], implementation: 'shared', addable: true }),
  imageOperator({ id: 'glyph.atlas', family: 'glyph.resource', variant: 'atlas', label: 'Glyph Atlas',
    description: 'Produces the existing cached glyph atlas and its transient layout metadata from bound effect-owned ramp and font parameters.',
    inputs: [], outputs: [port('image', 'image', 'Atlas'), port('glyphCount', 'number', 'Glyph Count'),
      port('columns', 'number', 'Columns'), port('rows', 'number', 'Rows')], parameters: [],
    consumers: ['image', 'glyph'], implementation: 'shared' }),
  imageOperator({ id: 'convert.image-to-vec4', label: 'Image to RGBA', description: 'Adapts one sampled image pixel to a four-component value.',
    inputs: [port('image', 'image', 'Image', true)], outputs: [port('value', 'vec4', 'RGBA')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.vec4-to-image', label: 'RGBA to Image', description: 'Adapts a four-component value to one image pixel.',
    inputs: [port('value', 'vec4', 'RGBA', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: true }),
  imageOperator({ id: 'vector.split.rgba', label: 'Split RGB + Alpha', description: 'Structurally separates an RGBA image value into source-encoded RGB and straight alpha.',
    inputs: [port('image', 'image', 'Image', true)], outputs: [port('rgb', 'rgb', 'RGB'), port('alpha', 'alpha', 'Alpha')], parameters: [], addable: true }),
  imageOperator({ id: 'vector.combine.rgba', label: 'Combine RGB + Alpha', description: 'Structurally combines RGB and alpha as an RGBA image value.',
    inputs: [port('rgb', 'rgb', 'RGB', true), port('alpha', 'alpha', 'Alpha', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: true }),
  imageOperator({ id: 'math.subtract.scalar', family: 'math.subtract', variant: 'scalar', label: 'Subtract', description: 'Subtracts scalar B from scalar A. This typed variant does not alias scalar-field math.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'mute' }),
  imageOperator({ id: 'math.subtract.rgb', family: 'math.subtract', variant: 'rgb', label: 'Subtract', description: 'Component-wise RGB subtraction in the shared subtract family. Bypass passes B through.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'mute' }),
  imageOperator({ id: 'math.add.rgb', family: 'math.add', variant: 'rgb', label: 'Add', description: 'Component-wise RGB addition preserving source color encoding.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.multiply.rgb', family: 'math.multiply', variant: 'rgb', label: 'Multiply', description: 'Component-wise RGB multiplication preserving source color encoding.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.clamp.rgb', family: 'math.clamp', variant: 'rgb', label: 'Clamp', description: 'Clamps each RGB component between the connected minimum and maximum.',
    inputs: [port('value', 'rgb', 'Value', true), port('min', 'rgb', 'Min', true), port('max', 'rgb', 'Max', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.mix.rgb', family: 'math.mix', variant: 'rgb', label: 'Mix', description: 'Linearly interpolates or extrapolates between RGB A and B using scalar T. Bypass passes B through.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true), port('t', 'number', 'T', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.mix.vec4', family: 'math.mix', variant: 'vec4', label: 'Mix', description: 'Linearly interpolates or extrapolates between vec4 A and B using scalar T. Bypass passes B through.',
    inputs: [port('a', 'vec4', 'A', true), port('b', 'vec4', 'B', true), port('t', 'number', 'T', true)], outputs: [port('value', 'vec4', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'color.luminance-rec601.rgb', family: 'color.luminance-rec601', variant: 'rgb', label: 'Rec.601 Luminance',
    description: 'Computes 0.299 R + 0.587 G + 0.114 B directly in the source color encoding.',
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('value', 'number', 'Luminance')], parameters: [], addable: true }),
  ...['add', 'multiply'].map(operation => imageOperator({ id: `math.${operation}.scalar`, family: `math.${operation}`, variant: 'scalar',
    label: operation === 'add' ? 'Add' : 'Multiply', description: `${operation} on two scalar values.`,
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' })),
  imageOperator({ id: 'math.divide-ieee.scalar', family: 'math.divide-ieee', variant: 'scalar', label: 'Divide (IEEE)',
    description: 'Unguarded scalar division matching legacy shader formulas; no safety epsilon is applied and singular GPU results are undefined.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  ...['reciprocal', 'exp2', 'fract'].map(operation => imageOperator({ id: `math.${operation}.scalar`, family: `math.${operation}`, variant: 'scalar',
    label: operation === 'exp2' ? 'Exp2' : `${operation[0].toUpperCase()}${operation.slice(1)}`, description: `${operation} of a scalar value.`,
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' })),
  imageOperator({ id: 'math.tan.scalar', family: 'math.tan', variant: 'scalar', label: 'Tangent',
    description: 'Raw tangent of a radians input with no implicit clamp or singularity guard.',
    inputs: [port('value', 'number', 'Radians', true)], outputs: [port('value', 'number', 'Value')], parameters: [],
    consumers: ['image', 'fisheye'], implementation: 'shared', addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.atan.scalar', family: 'math.atan', variant: 'scalar', label: 'Arctangent',
    description: 'Raw scalar arctangent producing radians with no implicit clamp or guard.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Radians')], parameters: [],
    consumers: ['image', 'fisheye'], implementation: 'shared', addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.abs.scalar', family: 'math.abs', variant: 'scalar', label: 'Absolute Value',
    description: 'Shared pure scalar absolute value; bounded scalar-field runtimes apply their existing output limit afterward.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [],
    consumers: ['image', 'fisheye'], implementation: 'shared', addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'convert.degrees-to-radians.scalar', family: 'convert.angle', variant: 'degrees-radians', label: 'Degrees to Radians',
    description: 'Explicitly converts a scalar angle from degrees to radians.',
    inputs: [port('value', 'number', 'Degrees', true)], outputs: [port('value', 'number', 'Radians')], parameters: [],
    consumers: ['image', 'fisheye'], implementation: 'shared', addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.divide-ieee.rgb', family: 'math.divide-ieee', variant: 'rgb', label: 'Divide (IEEE)', description: 'Unguarded component-wise RGB division with no safety epsilon; singular GPU results are undefined.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.max.rgb', family: 'math.max', variant: 'rgb', label: 'Maximum', description: 'Component-wise RGB maximum.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.power.rgb', family: 'math.power', variant: 'rgb', label: 'Power', description: 'Component-wise RGB exponentiation.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.mix-components.rgb', family: 'math.mix', variant: 'rgb-components', label: 'Mix Components',
    description: 'Component-wise RGB interpolation or extrapolation using an RGB factor.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true), port('t', 'rgb', 'T', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  ...['min', 'max'].map(operation => imageOperator({ id: `vector.reduce-${operation}.rgb`, family: `vector.reduce-${operation}`, variant: 'rgb',
    label: `${operation === 'min' ? 'Minimum' : 'Maximum'} RGB`, description: `Reduces RGB to its ${operation} component.`,
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true })),
  imageOperator({ id: 'convert.vec3-to-rgb', family: 'convert.vector-color', variant: 'vec3-rgb', label: 'Vector to RGB', description: 'Reinterprets three ordered components as source-encoded RGB.',
    inputs: [port('value', 'vec3', 'Vector', true)], outputs: [port('rgb', 'rgb', 'RGB')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.rgb-to-vec3', family: 'convert.vector-color', variant: 'rgb-vec3', label: 'RGB to Vector', description: 'Reinterprets source-encoded RGB as three ordered components.',
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('value', 'vec3', 'Vector')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.rgb-to-hsv', family: 'convert.rgb-hsv', variant: 'rgb-hsv', label: 'RGB to HSV', description: 'Converts source-encoded RGB to HSV with the legacy 1e-10 stabilization.',
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('value', 'vec3', 'HSV')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.hsv-to-rgb', family: 'convert.rgb-hsv', variant: 'hsv-rgb', label: 'HSV to RGB', description: 'Converts HSV to source-encoded RGB.',
    inputs: [port('value', 'vec3', 'HSV', true)], outputs: [port('rgb', 'rgb', 'RGB')], parameters: [], addable: true }),
  imageOperator({ id: 'color.luminance-rec709.rgb', family: 'color.luminance-rec709', variant: 'rgb', label: 'Rec.709 Luminance',
    description: 'Computes 0.2126 R + 0.7152 G + 0.0722 B directly in the source color encoding.',
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('value', 'number', 'Luminance')], parameters: [], addable: true }),
  imageOperator({ id: 'color.luminance-rec709.image', family: 'color.luminance-rec709', variant: 'image', label: 'Rec.709 Image Luminance',
    description: 'Computes Rec.709 luminance from the current source-encoded image pixel while ignoring alpha; no texture resampling occurs.',
    inputs: [port('image', 'image', 'Image', true)], outputs: [port('value', 'number', 'Luminance')], parameters: [], addable: true }),
  imageOperator({ id: 'image.segment-sort-luma', family: 'image.segment-sort', variant: 'stable-rec709-16', label: 'Stable Luma Segment Sort',
    description: 'Stably sorts up to 16 horizontal RGBA pixels by source-encoded Rec.709 luminance using strict greater-than comparisons; short segments duplicate their final pixel to fill the fixed 16-entry sort.',
    inputs: [port('image', 'image', 'Image', true), port('scale', 'number', 'Segment Size', true)], outputs: [port('image', 'image', 'Image')], parameters: [],
    consumers: ['image', 'pixel-sort'], implementation: 'shared', addable: false, bypass: 'passthrough' }),
  imageOperator({ id: 'image.quadtree-partition', family: 'image.spatial-partition', variant: 'quadtree-6', label: 'Quadtree Partition',
    description: 'Finds the containing image block through at most six conditional subdivisions, sampling corner pixels then center in exact legacy order at each visited level.',
    inputs: [port('image', 'image', 'Image', true), port('scale', 'number', 'Minimum Size', true), port('threshold', 'number', 'Threshold', true),
      port('time', 'number', 'Timeline Time', true), port('speed', 'number', 'Speed', true)],
    outputs: [port('origin', 'vec2', 'Pixel Origin'), port('size', 'number', 'Block Size')], parameters: [],
    consumers: ['image', 'quadtree-zoom'], implementation: 'shared', addable: false }),
  imageOperator({ id: 'geometry.marching-squares-topology', family: 'geometry.marching-squares', variant: 'binary-table', label: 'Marching Squares Topology',
    description: 'Selects up to two contour segments from four binary corner occupancies and four interpolated edge points using the shared fixed topology table.',
    inputs: [port('tl', 'number', 'Top Left', true), port('tr', 'number', 'Top Right', true), port('br', 'number', 'Bottom Right', true),
      port('bl', 'number', 'Bottom Left', true), port('top', 'vec2', 'Top', true), port('right', 'vec2', 'Right', true),
      port('bottom', 'vec2', 'Bottom', true), port('left', 'vec2', 'Left', true)],
    outputs: [port('a', 'vec2', 'Segment A'), port('b', 'vec2', 'Segment B'), port('c', 'vec2', 'Segment C'),
      port('d', 'vec2', 'Segment D'), port('count', 'number', 'Segment Count')], parameters: [],
    consumers: ['image', 'contour'], implementation: 'shared', addable: false }),
  imageOperator({ id: 'compare.greater.scalar', family: 'compare.greater', variant: 'scalar', label: 'Greater Than',
    description: 'Returns true only when scalar A is strictly greater than scalar B.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('condition', 'boolean', 'Condition')], parameters: [], addable: true }),
  imageOperator({ id: 'select.scalar', family: 'select', variant: 'scalar', label: 'Select', description: 'Selects the true or false scalar from a strict Boolean condition.',
    inputs: [port('falseValue', 'number', 'False', true), port('trueValue', 'number', 'True', true), port('condition', 'boolean', 'Condition', true)],
    outputs: [port('value', 'number', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'select.vec2', family: 'select', variant: 'vec2', label: 'Select Vector 2', description: 'Eagerly selects one vec2 from a strict Boolean condition.',
    inputs: [port('falseValue', 'vec2', 'False', true), port('trueValue', 'vec2', 'True', true), port('condition', 'boolean', 'Condition', true)],
    outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'math.max.scalar', family: 'math.max', variant: 'scalar', label: 'Maximum', description: 'Returns the larger scalar value.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.min.scalar', family: 'math.min', variant: 'scalar', label: 'Minimum', description: 'Returns the smaller scalar value.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.power.scalar', family: 'math.power', variant: 'scalar', label: 'Power', description: 'Raw scalar exponentiation without signed or field safeguards.',
    inputs: [port('a', 'number', 'Base', true), port('b', 'number', 'Exponent', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.atan2.scalar', family: 'math.atan2', variant: 'scalar', label: 'Atan2', description: 'Oriented angle in radians using explicit Y then X inputs.',
    inputs: [port('y', 'number', 'Y', true), port('x', 'number', 'X', true)], outputs: [port('value', 'number', 'Radians')], parameters: [], addable: true }),
  imageOperator({ id: 'coordinates.rotate.vec2', family: 'coordinates.rotate', variant: 'vec2', label: 'Rotate Coordinates',
    description: 'Rotates a two-component coordinate around the origin by an angle in radians.',
    inputs: [port('value', 'vec2', 'Value', true), port('angle', 'number', 'Angle', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [],
    consumers: ['image', 'fisheye'], implementation: 'shared', addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'coordinates.integer-cell-origin.vec2', family: 'coordinates.cell-origin', variant: 'integer-vec2', label: 'Integer Cell Origin',
    description: 'Returns the origin of a positive integer-sized pixel cell using exact signed-integer division and multiplication.',
    inputs: [port('pixel', 'vec2', 'Pixel', true), port('size', 'number', 'Size', true)], outputs: [port('value', 'vec2', 'Origin')],
    parameters: [], consumers: ['image'], implementation: 'shared', addable: true }),
  imageOperator({ id: 'optics.project-radius.scalar', family: 'optics.radial-projection', variant: 'project', label: 'Project Radius',
    description: 'Maps an optical angle in radians to normalized lens radius: model 0 equidistant, 1 equisolid, 2 stereographic, 3 orthographic.',
    inputs: [port('theta', 'number', 'Theta', true), port('maxTheta', 'number', 'Maximum Theta', true), port('model', 'number', 'Model', true)],
    outputs: [port('value', 'number', 'Radius')], parameters: [], consumers: ['image', 'fisheye'], implementation: 'shared', addable: true }),
  imageOperator({ id: 'optics.unproject-radius.scalar', family: 'optics.radial-projection', variant: 'unproject', label: 'Unproject Radius',
    description: 'Maps normalized lens radius back to radians: model 0 equidistant, 1 equisolid, 2 stereographic, 3 orthographic.',
    inputs: [port('radius', 'number', 'Radius', true), port('maxTheta', 'number', 'Maximum Theta', true), port('model', 'number', 'Model', true)],
    outputs: [port('value', 'number', 'Theta')], parameters: [], consumers: ['image', 'fisheye'], implementation: 'shared', addable: true }),
  imageOperator({ id: 'math.clamp.scalar', family: 'math.clamp', variant: 'scalar', label: 'Clamp',
    description: 'Clamps a scalar between normalized minimum and maximum bounds.', inputs: [port('value', 'number', 'Value', true),
      port('min', 'number', 'Min', true), port('max', 'number', 'Max', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.sqrt.scalar', family: 'math.sqrt', variant: 'scalar', label: 'Square Root',
    description: 'Computes the ordinary scalar square root without hidden clamping.', inputs: [port('value', 'number', 'Value', true)],
    outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.floor.rgb', family: 'math.floor', variant: 'rgb', label: 'Floor', description: 'Rounds every RGB component down to the nearest integer.',
    inputs: [port('value', 'rgb', 'Value', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'image.normalized-uv', family: 'image.coordinates', variant: 'normalized-uv', label: 'Normalized Coordinates',
    description: 'Current fragment coordinates normalized to the source image extent; no texture mapping transform is applied.',
    inputs: [], outputs: [port('uv', 'vec2', 'UV')], parameters: [], addable: true }),
  imageOperator({ id: 'image.timeline-time', family: 'image.context', variant: 'timeline-time', label: 'Timeline Time',
    description: 'Current deterministic composition timeline time in seconds.', inputs: [], outputs: [port('value', 'number', 'Seconds')], parameters: [], addable: true }),
  imageOperator({ id: 'image.resolution', family: 'image.context', variant: 'resolution', label: 'Image Resolution',
    description: 'Current source width and height in pixels.', inputs: [], outputs: [port('value', 'vec2', 'Resolution')], parameters: [], addable: true }),
  ...(['auto', 'fine', 'coarse'] as const).map(mode => imageOperator({
    id: `image.derivative.${mode}.scalar`, family: 'image.derivative', variant: mode,
    label: `${mode[0].toUpperCase()}${mode.slice(1)} Scalar Derivative`,
    description: mode === 'auto'
      ? 'Returns native automatic screen-space scalar derivatives; CPU evaluation requires an explicit fine or coarse policy.'
      : `Returns native ${mode} screen-space scalar derivatives across the current fragment quad.`,
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('gradient', 'vec2', 'Gradient')], parameters: [], addable: true,
  })),
  imageOperator({ id: 'image.sample', family: 'image.sample', variant: 'uv', label: 'Sample Image',
    description: 'Re-evaluates a connected pure image expression at normalized UV coordinates without an intermediate pass.',
    inputs: [port('image', 'image', 'Image', true), port('uv', 'vec2', 'UV', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'image.load-pixel-clamped', family: 'image.sample', variant: 'pixel-clamped', label: 'Load Pixel',
    description: 'Re-evaluates a connected image expression at integer-truncated pixel coordinates clamped to the current image extent.',
    inputs: [port('image', 'image', 'Image', true), port('pixel', 'vec2', 'Pixel', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'image.named-input', label: 'Named Image Input',
    description: 'Reads a compile-context image resource using its declared sampling contract.',
    inputs: [], outputs: [port('image', 'image', 'Image')], parameters: [], addable: false }),
  imageOperator({ id: 'source.memory-window', family: 'source.memory', variant: 'window', label: 'Memory Window',
    description: 'Produces an exact unsigned-word texture plus dynamic availability and dimensions from effect-owned memory settings.', inputs: [],
    outputs: [port('memory', 'uint32-texture', 'Memory'), port('metadata', 'vec4', 'Metadata')], parameters: [], addable: false,
    consumers: ['image', 'memory-leak'], implementation: 'shared' }),
  imageOperator({ id: 'data.decode-byte-pixel', family: 'data.decode', variant: 'byte-pixel', label: 'Decode Byte Pixel',
    description: 'Decodes one 8-bit, 16-bit, or four-word float RGBA pixel from an exact unsigned-word texture.',
    inputs: [port('memory', 'uint32-texture', 'Memory', true), port('pixel', 'vec2', 'Pixel', true), port('depth', 'number', 'Depth', true),
      port('floatMode', 'number', 'Float Mode', true), port('floatGain', 'number', 'Float Gain', true)], outputs: [port('value', 'vec4', 'RGBA')],
    parameters: [], addable: false, consumers: ['image', 'memory-leak'], implementation: 'shared' }),
  { ...imageOperator({ id: 'image.frame-history', family: 'image.source', variant: 'frame-history', label: 'Frame History',
    description: 'Reads the previous committed output owned by the current effect history scope.',
    inputs: [], outputs: [port('image', 'image', 'Image')], parameters: [], addable: false,
    consumers: ['image'], implementation: 'shared' }), state: 'frame-history', fusion: 'pass-boundary' },
  { ...imageOperator({ id: 'image.materialize', family: 'image.materialize', variant: 'rgba16float', label: 'Materialize Image',
    description: 'Stores an image expression in an internal rgba16float resource before downstream evaluation.',
    inputs: [port('image', 'image', 'Image', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: true }), fusion: 'pass-boundary' },
  imageOperator({ id: 'image.resource-input', label: 'Materialized Resource', description: 'Compiler-owned materialized image input.',
    inputs: [], outputs: [port('image', 'image', 'Image')], parameters: [], addable: false }),
  imageOperator({ id: 'image.kernel-index', family: 'image.kernel', variant: 'index', label: 'Kernel Index',
    description: 'Current integer XY offset inside a kernel reduction scope.', inputs: [], outputs: [port('value', 'vec2', 'Index')], parameters: [], addable: true }),
  imageOperator({ id: 'image.kernel-grid-reduce', family: 'image.kernel', variant: 'grid-reduce', label: 'Kernel Grid Reduce',
    description: 'Evaluates sample and weight once per grid offset; extent is truncated and clamped to 0..64 before weighted RGBA and weight accumulation.',
    inputs: [port('sample', 'image', 'Sample', true), port('weight', 'number', 'Weight', true), port('extent', 'number', 'Extent', true)],
    outputs: [port('sum', 'vec4', 'Sum'), port('weightSum', 'number', 'Weight Sum')], parameters: [], addable: true }),
  imageOperator({ id: 'image.kernel-rect-reduce', family: 'image.kernel', variant: 'rect-reduce', label: 'Rectangular Kernel Reduce',
    description: 'Evaluates sample and weight over a 1..64 by 1..64 zero-based rectangular domain, X outer and Y inner.',
    inputs: [port('sample', 'image', 'Sample', true), port('weight', 'number', 'Weight', true), port('width', 'number', 'Width', true), port('height', 'number', 'Height', true)],
    outputs: [port('sum', 'vec4', 'Sum'), port('weightSum', 'number', 'Weight Sum')], parameters: [], addable: true }),
  imageOperator({ id: 'image.sequence-index', family: 'image.sequence', variant: 'index', label: 'Sequence Index',
    description: 'Current zero-based index and normalized progress inside a sequence reduction scope.', inputs: [],
    outputs: [port('index', 'number', 'Index'), port('t', 'number', 'Progress')], parameters: [], addable: true }),
  imageOperator({ id: 'image.sequence-reduce', family: 'image.sequence', variant: 'reduce', label: 'Sequence Reduce',
    description: 'Evaluates sample and weight once for each of 1..256 sequence entries and accumulates weighted RGBA plus total weight.',
    inputs: [port('sample', 'image', 'Sample', true), port('weight', 'number', 'Weight', true), port('count', 'number', 'Count', true)],
    outputs: [port('sum', 'vec4', 'Sum'), port('weightSum', 'number', 'Weight Sum')], parameters: [], addable: true }),
  imageOperator({ id: 'coordinates.mirror-repeat.vec2', family: 'coordinates.mirror-repeat', variant: 'vec2', label: 'Mirror Repeat',
    description: 'Mirrors each coordinate into 0..1 using the legacy two-unit repeat formula.', inputs: [port('value', 'vec2', 'Value', true)],
    outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'control.select.image', family: 'control.select', variant: 'image', label: 'Select Image',
    description: 'Lazily evaluates only the selected image branch.', inputs: [port('condition', 'boolean', 'Condition', true),
      port('falseValue', 'image', 'False', true), port('trueValue', 'image', 'True', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: true }),
  imageOperator({ id: 'control.select.scalar', family: 'control.select', variant: 'scalar', label: 'Select Scalar',
    description: 'Lazily evaluates only the selected scalar branch.', inputs: [port('condition', 'boolean', 'Condition', true),
      port('falseValue', 'number', 'False', true), port('trueValue', 'number', 'True', true)], outputs: [port('value', 'number', 'Value')],
    parameters: [], consumers: ['image'], implementation: 'shared', addable: true }),
  imageOperator({ id: 'values.boolean', family: 'values', variant: 'boolean', label: 'Boolean', description: 'A literal or effect-bound Boolean value.',
    inputs: [], outputs: [port('value', 'boolean', 'Value')], parameters: [{ id: 'value', label: 'Value', type: 'boolean', default: false }], addable: true }),
  imageOperator({ id: 'values.choice', family: 'values', variant: 'choice', label: 'Choice',
    description: 'Outputs the ordered numeric index of a bound effect select parameter.', inputs: [], outputs: [port('value', 'number', 'Value')],
    parameters: [{ id: 'value', label: 'Value', type: 'select', default: '' }], addable: false }),
  imageOperator({ id: 'values.color', family: 'values', variant: 'color', label: 'Color', description: 'A source-encoded RGBA color value.',
    inputs: [], outputs: [port('value', 'vec4', 'Color')], parameters: [{ id: 'value', label: 'Color', type: 'color', default: '#111827' }], addable: true }),
  ...['subtract', 'multiply'].map(operation => imageOperator({ id: `math.${operation}.vec2`, family: `math.${operation}`, variant: 'vec2',
    label: operation === 'subtract' ? 'Subtract' : 'Multiply', description: `Component-wise vec2 ${operation}.`,
    inputs: [port('a', 'vec2', 'A', true), port('b', 'vec2', 'B', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' })),
  imageOperator({ id: 'math.add.vec2', family: 'math.add', variant: 'vec2', label: 'Add', description: 'Component-wise vec2 addition.',
    inputs: [port('a', 'vec2', 'A', true), port('b', 'vec2', 'B', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.divide-ieee.vec2', family: 'math.divide-ieee', variant: 'vec2', label: 'Divide (IEEE)', description: 'Unguarded component-wise vec2 division.',
    inputs: [port('a', 'vec2', 'A', true), port('b', 'vec2', 'B', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.divide-ieee.vec2-scalar', family: 'math.divide-ieee', variant: 'vec2-scalar', label: 'Divide by Scalar (IEEE)',
    description: 'Unguarded vec2 division by one scalar using IEEE semantics.', inputs: [port('a', 'vec2', 'A', true), port('b', 'number', 'B', true)],
    outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough',
    consumers: ['image', 'fisheye'], implementation: 'shared' }),
  imageOperator({ id: 'math.floor.vec2', family: 'math.floor', variant: 'vec2', label: 'Floor', description: 'Rounds both vec2 components down.',
    inputs: [port('value', 'vec2', 'Value', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.fract.vec2', family: 'math.fract', variant: 'vec2', label: 'Fraction', description: 'Fractional part of both vec2 components.',
    inputs: [port('value', 'vec2', 'Value', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.clamp.vec2', family: 'math.clamp', variant: 'vec2', label: 'Clamp', description: 'Clamps vec2 between component-wise bounds.',
    inputs: [port('value', 'vec2', 'Value', true), port('min', 'vec2', 'Min', true), port('max', 'vec2', 'Max', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'vector.reduce-min.vec2', family: 'vector.reduce-min', variant: 'vec2', label: 'Minimum', description: 'Returns the smaller vec2 component.',
    inputs: [port('value', 'vec2', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'noise.hash2d.vec2', family: 'noise.hash2d', variant: 'vec2', label: 'Hash 2D', description: 'Deterministic shared two-dimensional sine hash.',
    inputs: [port('value', 'vec2', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'vector.dot.vec2', family: 'vector.dot', variant: 'vec2', label: 'Dot Product', description: 'Dot product of two vec2 values.',
    inputs: [port('a', 'vec2', 'A', true), port('b', 'vec2', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'math.sin.scalar', family: 'math.sin', variant: 'scalar', label: 'Sine', description: 'Sine of a scalar angle in radians.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.cos.scalar', family: 'math.cos', variant: 'scalar', label: 'Cosine', description: 'Cosine of a scalar angle in radians.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.exp.scalar', family: 'math.exp', variant: 'scalar', label: 'Exponential', description: 'Natural exponential of a scalar.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.gaussian.scalar', family: 'math.gaussian', variant: 'scalar', label: 'Gaussian',
    description: 'Evaluates exp(-(value²)/((2×sigma)×sigma)), matching the shared shader Gaussian.',
    inputs: [port('value', 'number', 'Value', true), port('sigma', 'number', 'Sigma', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'vector.unit-direction.scalar', family: 'vector.unit-direction', variant: 'scalar-angle', label: 'Unit Direction',
    description: 'Creates vec2(cos(angle), sin(angle)) from a scalar angle in radians.', inputs: [port('angle', 'number', 'Angle', true)],
    outputs: [port('value', 'vec2', 'Direction')], parameters: [], addable: true }),
  imageOperator({ id: 'math.divide-ieee.vec4', family: 'math.divide-ieee', variant: 'vec4', label: 'Divide (IEEE)',
    description: 'Unguarded component-wise vec4 division.', inputs: [port('a', 'vec4', 'A', true), port('b', 'vec4', 'B', true)],
    outputs: [port('value', 'vec4', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.multiply.vec4', family: 'math.multiply', variant: 'vec4', label: 'Multiply', description: 'Component-wise vec4 multiplication.',
    inputs: [port('a', 'vec4', 'A', true), port('b', 'vec4', 'B', true)], outputs: [port('value', 'vec4', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.multiply.image-scalar', family: 'math.multiply', variant: 'image-scalar', label: 'Multiply Image by Scalar', description: 'Scales all RGBA components by one scalar.',
    inputs: [port('a', 'image', 'Image', true), port('b', 'number', 'Scalar', true)], outputs: [port('value', 'image', 'Image')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.multiply.rgb-scalar', family: 'math.multiply', variant: 'rgb-scalar', label: 'Multiply RGB by Scalar', description: 'Scales all RGB components by one scalar.',
    inputs: [port('a', 'rgb', 'RGB', true), port('b', 'number', 'Scalar', true)], outputs: [port('value', 'rgb', 'RGB')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.multiply.vec2-scalar', family: 'math.multiply', variant: 'vec2-scalar', label: 'Multiply Vector by Scalar', description: 'Scales both vec2 components by one scalar.',
    inputs: [port('a', 'vec2', 'Vector', true), port('b', 'number', 'Scalar', true)], outputs: [port('value', 'vec2', 'Vector')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.divide-ieee.rgb-scalar', family: 'math.divide-ieee', variant: 'rgb-scalar', label: 'Divide RGB by Scalar', description: 'Unguarded RGB division by one scalar.',
    inputs: [port('a', 'rgb', 'RGB', true), port('b', 'number', 'Scalar', true)], outputs: [port('value', 'rgb', 'RGB')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.clamp.rgb-scalar', family: 'math.clamp', variant: 'rgb-scalar', label: 'Clamp RGB by Scalars', description: 'Clamps RGB using normalized scalar bounds.',
    inputs: [port('value', 'rgb', 'RGB', true), port('min', 'number', 'Min', true), port('max', 'number', 'Max', true)], outputs: [port('value', 'rgb', 'RGB')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'convert.vec4-to-rgb', family: 'convert.vector-color', variant: 'vec4-rgb', label: 'Vector 4 to RGB', description: 'Reads the first three vec4 components as RGB.',
    inputs: [port('value', 'vec4', 'RGBA', true)], outputs: [port('rgb', 'rgb', 'RGB')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.scalar-to-vec4', family: 'convert.scalar-vector', variant: 'vec4', label: 'Scalar to Vector 4',
    description: 'Replicates one scalar into four vector components.', inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'vec4', 'Vector')], parameters: [], addable: true }),
  imageOperator({ id: 'math.floor.scalar', family: 'math.floor', variant: 'scalar', label: 'Floor', description: 'Rounds a scalar down.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.round-even.scalar', family: 'math.round', variant: 'nearest-even-scalar', label: 'Round to Even',
    description: 'Rounds a finite f32 scalar to the nearest integer; exact halfway cases select the even integer.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [],
    consumers: ['image'], implementation: 'shared', addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.step.scalar', family: 'math.step', variant: 'scalar', label: 'Step', description: 'Returns zero below edge and one at or above edge.',
    inputs: [port('edge', 'number', 'Edge', true), port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'logic.and.boolean', family: 'logic.and', variant: 'boolean', label: 'And', description: 'True only when both Boolean inputs are true.',
    inputs: [port('a', 'boolean', 'A', true), port('b', 'boolean', 'B', true)], outputs: [port('value', 'boolean', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'vector.length.vec2', family: 'vector.length', variant: 'vec2', label: 'Length', description: 'Euclidean length of a two-component vector.',
    inputs: [port('value', 'vec2', 'Value', true)], outputs: [port('value', 'number', 'Length')], parameters: [], addable: true }),
  imageOperator({ id: 'math.smoothstep.scalar', family: 'math.smoothstep', variant: 'scalar', label: 'Smoothstep',
    description: 'Hermite interpolation from zero to one between ordered scalar edges; equal or reversed edges retain unguarded WGSL semantics.',
    inputs: [port('edge0', 'number', 'Edge 0', true), port('edge1', 'number', 'Edge 1', true), port('value', 'number', 'Value', true)],
    outputs: [port('value', 'number', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'math.mix.scalar', family: 'math.mix', variant: 'scalar', label: 'Mix', description: 'Scalar linear interpolation or extrapolation.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true), port('t', 'number', 'T', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'convert.scalar-to-vec2', family: 'convert.scalar-vector', variant: 'vec2', label: 'Scalar to Vector 2', description: 'Replicates one scalar into two vector components.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'vec2', 'Vector')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.scalar-to-rgb', label: 'Scalar to RGB', description: 'Replicates one scalar into three RGB components.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('rgb', 'rgb', 'RGB')], parameters: [], addable: true }),
  // Read-only migration definitions. migrateImageOperatorGraph removes them before canonical persistence/compilation.
  imageOperator({ id: 'image.rgb-split', label: 'Legacy Split RGB + Alpha', description: 'Migrates to vector.split.rgba.',
    inputs: [port('image', 'image', 'Image', true)], outputs: [port('rgb', 'rgb', 'RGB'), port('alpha', 'alpha', 'Alpha')], parameters: [], addable: false }),
  imageOperator({ id: 'image.rgb-combine', label: 'Legacy Combine RGB + Alpha', description: 'Migrates to vector.combine.rgba.',
    inputs: [port('rgb', 'rgb', 'RGB', true), port('alpha', 'alpha', 'Alpha', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: false }),
  imageOperator({ id: 'color.invert.rgb', label: 'Legacy RGB Invert', description: 'Migrates to scalar one, RGB splat and typed subtract.',
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('rgb', 'rgb', 'RGB')], parameters: [], addable: false, bypass: 'mute' }),
  imageOperator({ id: 'image.output', label: 'Image Output', description: 'Selects the image produced by this local graph.',
    inputs: [port('image', 'image', 'Image', true)], outputs: [], parameters: [], addable: false }),
];
