import type { OperatorDefinition, OperatorPort } from '../../types/operatorGraph';

const port = (id: string, type: OperatorPort['type'], label: string, required = false): OperatorPort =>
  ({ id, type, label, required });

const imageOperator = (definition: Omit<OperatorDefinition, 'version' | 'invalidates' | 'runtime' | 'state' | 'fusion'>): OperatorDefinition => ({
  ...definition,
  version: 1,
  invalidates: 'appearance',
  runtime: 'builtin',
  state: 'stateless',
  fusion: 'inline',
});

const vectorOperators = ([2, 3, 4] as const).flatMap(size => {
  const type = `vec${size}` as 'vec2' | 'vec3' | 'vec4';
  const components = ['x', 'y', 'z', 'w'].slice(0, size);
  return [
    imageOperator({ id: `vector.split.${type}`, family: 'vector.split', variant: type, label: `Split ${type.toUpperCase()}`, description: `Separates ${size} ordered vector components.`,
      inputs: [port('value', type, 'Value', true)], outputs: components.map(id => port(id, 'number', id.toUpperCase())), parameters: [], addable: true }),
    imageOperator({ id: `vector.combine.${type}`, family: 'vector.combine', variant: type, label: `Combine ${type.toUpperCase()}`, description: `Combines ${size} scalars into one ordered vector.`,
      inputs: components.map(id => port(id, 'number', id.toUpperCase(), true)), outputs: [port('value', type, 'Value')], parameters: [], addable: true }),
  ];
});

/** Operators newly owned by the local image compiler. image.frame and values.number stay canonical registry entries. */
export const IMAGE_OPERATORS: readonly OperatorDefinition[] = [
  ...vectorOperators,
  imageOperator({ id: 'convert.image-to-vec4', label: 'Image to RGBA', description: 'Adapts one sampled image pixel to a four-component value.',
    inputs: [port('image', 'image', 'Image', true)], outputs: [port('value', 'vec4', 'RGBA')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.vec4-to-image', label: 'RGBA to Image', description: 'Adapts a four-component value to one image pixel.',
    inputs: [port('value', 'vec4', 'RGBA', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: true }),
  imageOperator({ id: 'vector.split.rgba', label: 'Split RGB + Alpha', description: 'Structurally separates an RGBA image value into source-encoded RGB and straight alpha.',
    inputs: [port('image', 'image', 'Image', true)], outputs: [port('rgb', 'rgb', 'RGB'), port('alpha', 'alpha', 'Alpha')], parameters: [], addable: true }),
  imageOperator({ id: 'vector.combine.rgba', label: 'Combine RGB + Alpha', description: 'Structurally combines RGB and alpha as an RGBA image value.',
    inputs: [port('rgb', 'rgb', 'RGB', true), port('alpha', 'alpha', 'Alpha', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: true }),
  imageOperator({ id: 'math.subtract.scalar', family: 'math.subtract', variant: 'scalar', label: 'Subtract', description: 'Subtracts scalar B from scalar A. This typed variant does not alias scalar-field math.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'mute' }),
  imageOperator({ id: 'math.subtract.rgb', family: 'math.subtract', variant: 'rgb', label: 'Subtract', description: 'Component-wise RGB subtraction in the shared subtract family. Bypass passes B through.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'mute' }),
  imageOperator({ id: 'math.add.rgb', family: 'math.add', variant: 'rgb', label: 'Add', description: 'Component-wise RGB addition preserving source color encoding.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.multiply.rgb', family: 'math.multiply', variant: 'rgb', label: 'Multiply', description: 'Component-wise RGB multiplication preserving source color encoding.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.clamp.rgb', family: 'math.clamp', variant: 'rgb', label: 'Clamp', description: 'Clamps each RGB component between the connected minimum and maximum.',
    inputs: [port('value', 'rgb', 'Value', true), port('min', 'rgb', 'Min', true), port('max', 'rgb', 'Max', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.mix.rgb', family: 'math.mix', variant: 'rgb', label: 'Mix', description: 'Linearly interpolates or extrapolates between RGB A and B using scalar T. Bypass passes B through.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true), port('t', 'number', 'T', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'color.luminance-rec601.rgb', family: 'color.luminance-rec601', variant: 'rgb', label: 'Rec.601 Luminance',
    description: 'Computes 0.299 R + 0.587 G + 0.114 B directly in the source color encoding.',
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('value', 'number', 'Luminance')], parameters: [], addable: true }),
  ...['add', 'multiply'].map(operation => imageOperator({ id: `math.${operation}.scalar`, family: `math.${operation}`, variant: 'scalar',
    label: operation === 'add' ? 'Add' : 'Multiply', description: `${operation} on two scalar values.`,
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' })),
  imageOperator({ id: 'math.divide-ieee.scalar', family: 'math.divide-ieee', variant: 'scalar', label: 'Divide (IEEE)',
    description: 'Unguarded scalar division matching legacy shader formulas; no safety epsilon is applied and singular GPU results are undefined.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  ...['reciprocal', 'exp2', 'fract'].map(operation => imageOperator({ id: `math.${operation}.scalar`, family: `math.${operation}`, variant: 'scalar',
    label: operation === 'exp2' ? 'Exp2' : `${operation[0].toUpperCase()}${operation.slice(1)}`, description: `${operation} of a scalar value.`,
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' })),
  imageOperator({ id: 'math.divide-ieee.rgb', family: 'math.divide-ieee', variant: 'rgb', label: 'Divide (IEEE)', description: 'Unguarded component-wise RGB division with no safety epsilon; singular GPU results are undefined.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.max.rgb', family: 'math.max', variant: 'rgb', label: 'Maximum', description: 'Component-wise RGB maximum.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.power.rgb', family: 'math.power', variant: 'rgb', label: 'Power', description: 'Component-wise RGB exponentiation.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.mix-components.rgb', family: 'math.mix', variant: 'rgb-components', label: 'Mix Components',
    description: 'Component-wise RGB interpolation or extrapolation using an RGB factor.',
    inputs: [port('a', 'rgb', 'A', true), port('b', 'rgb', 'B', true), port('t', 'rgb', 'T', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  ...['min', 'max'].map(operation => imageOperator({ id: `vector.reduce-${operation}.rgb`, family: `vector.reduce-${operation}`, variant: 'rgb',
    label: `${operation === 'min' ? 'Minimum' : 'Maximum'} RGB`, description: `Reduces RGB to its ${operation} component.`,
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true })),
  imageOperator({ id: 'convert.vec3-to-rgb', family: 'convert.vector-color', variant: 'vec3-rgb', label: 'Vector to RGB', description: 'Reinterprets three ordered components as source-encoded RGB.',
    inputs: [port('value', 'vec3', 'Vector', true)], outputs: [port('rgb', 'rgb', 'RGB')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.rgb-to-vec3', family: 'convert.vector-color', variant: 'rgb-vec3', label: 'RGB to Vector', description: 'Reinterprets source-encoded RGB as three ordered components.',
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('value', 'vec3', 'Vector')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.rgb-to-hsv', family: 'convert.rgb-hsv', variant: 'rgb-hsv', label: 'RGB to HSV', description: 'Converts source-encoded RGB to HSV with the legacy 1e-10 stabilization.',
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('value', 'vec3', 'HSV')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.hsv-to-rgb', family: 'convert.rgb-hsv', variant: 'hsv-rgb', label: 'HSV to RGB', description: 'Converts HSV to source-encoded RGB.',
    inputs: [port('value', 'vec3', 'HSV', true)], outputs: [port('rgb', 'rgb', 'RGB')], parameters: [], addable: true }),
  imageOperator({ id: 'color.luminance-rec709.rgb', family: 'color.luminance-rec709', variant: 'rgb', label: 'Rec.709 Luminance',
    description: 'Computes 0.2126 R + 0.7152 G + 0.0722 B directly in the source color encoding.',
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('value', 'number', 'Luminance')], parameters: [], addable: true }),
  imageOperator({ id: 'compare.greater.scalar', family: 'compare.greater', variant: 'scalar', label: 'Greater Than',
    description: 'Returns true only when scalar A is strictly greater than scalar B.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('condition', 'boolean', 'Condition')], parameters: [], addable: true }),
  imageOperator({ id: 'select.scalar', family: 'select', variant: 'scalar', label: 'Select', description: 'Selects the true or false scalar from a strict Boolean condition.',
    inputs: [port('falseValue', 'number', 'False', true), port('trueValue', 'number', 'True', true), port('condition', 'boolean', 'Condition', true)],
    outputs: [port('value', 'number', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'math.max.scalar', family: 'math.max', variant: 'scalar', label: 'Maximum', description: 'Returns the larger scalar value.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.floor.rgb', family: 'math.floor', variant: 'rgb', label: 'Floor', description: 'Rounds every RGB component down to the nearest integer.',
    inputs: [port('value', 'rgb', 'Value', true)], outputs: [port('value', 'rgb', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'image.normalized-uv', family: 'image.coordinates', variant: 'normalized-uv', label: 'Normalized Coordinates',
    description: 'Current fragment coordinates normalized to the source image extent; no texture mapping transform is applied.',
    inputs: [], outputs: [port('uv', 'vec2', 'UV')], parameters: [], addable: true }),
  imageOperator({ id: 'image.timeline-time', family: 'image.context', variant: 'timeline-time', label: 'Timeline Time',
    description: 'Current deterministic composition timeline time in seconds.', inputs: [], outputs: [port('value', 'number', 'Seconds')], parameters: [], addable: true }),
  imageOperator({ id: 'image.resolution', family: 'image.context', variant: 'resolution', label: 'Image Resolution',
    description: 'Current source width and height in pixels.', inputs: [], outputs: [port('value', 'vec2', 'Resolution')], parameters: [], addable: true }),
  imageOperator({ id: 'image.sample', family: 'image.sample', variant: 'uv', label: 'Sample Image',
    description: 'Re-evaluates a connected pure image expression at normalized UV coordinates without an intermediate pass.',
    inputs: [port('image', 'image', 'Image', true), port('uv', 'vec2', 'UV', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'values.boolean', family: 'values', variant: 'boolean', label: 'Boolean', description: 'A literal or effect-bound Boolean value.',
    inputs: [], outputs: [port('value', 'boolean', 'Value')], parameters: [{ id: 'value', label: 'Value', type: 'boolean', default: false }], addable: true }),
  ...['subtract', 'multiply'].map(operation => imageOperator({ id: `math.${operation}.vec2`, family: `math.${operation}`, variant: 'vec2',
    label: operation === 'subtract' ? 'Subtract' : 'Multiply', description: `Component-wise vec2 ${operation}.`,
    inputs: [port('a', 'vec2', 'A', true), port('b', 'vec2', 'B', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' })),
  imageOperator({ id: 'math.add.vec2', family: 'math.add', variant: 'vec2', label: 'Add', description: 'Component-wise vec2 addition.',
    inputs: [port('a', 'vec2', 'A', true), port('b', 'vec2', 'B', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.divide-ieee.vec2', family: 'math.divide-ieee', variant: 'vec2', label: 'Divide (IEEE)', description: 'Unguarded component-wise vec2 division.',
    inputs: [port('a', 'vec2', 'A', true), port('b', 'vec2', 'B', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.floor.vec2', family: 'math.floor', variant: 'vec2', label: 'Floor', description: 'Rounds both vec2 components down.',
    inputs: [port('value', 'vec2', 'Value', true)], outputs: [port('value', 'vec2', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'vector.dot.vec2', family: 'vector.dot', variant: 'vec2', label: 'Dot Product', description: 'Dot product of two vec2 values.',
    inputs: [port('a', 'vec2', 'A', true), port('b', 'vec2', 'B', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'math.sin.scalar', family: 'math.sin', variant: 'scalar', label: 'Sine', description: 'Sine of a scalar angle in radians.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'math.cos.scalar', family: 'math.cos', variant: 'scalar', label: 'Cosine', description: 'Cosine of a scalar angle in radians.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'logic.and.boolean', family: 'logic.and', variant: 'boolean', label: 'And', description: 'True only when both Boolean inputs are true.',
    inputs: [port('a', 'boolean', 'A', true), port('b', 'boolean', 'B', true)], outputs: [port('value', 'boolean', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'vector.length.vec2', family: 'vector.length', variant: 'vec2', label: 'Length', description: 'Euclidean length of a two-component vector.',
    inputs: [port('value', 'vec2', 'Value', true)], outputs: [port('value', 'number', 'Length')], parameters: [], addable: true }),
  imageOperator({ id: 'math.smoothstep.scalar', family: 'math.smoothstep', variant: 'scalar', label: 'Smoothstep',
    description: 'Hermite interpolation from zero to one between ordered scalar edges; equal or reversed edges retain unguarded WGSL semantics.',
    inputs: [port('edge0', 'number', 'Edge 0', true), port('edge1', 'number', 'Edge 1', true), port('value', 'number', 'Value', true)],
    outputs: [port('value', 'number', 'Value')], parameters: [], addable: true }),
  imageOperator({ id: 'math.mix.scalar', family: 'math.mix', variant: 'scalar', label: 'Mix', description: 'Scalar linear interpolation or extrapolation.',
    inputs: [port('a', 'number', 'A', true), port('b', 'number', 'B', true), port('t', 'number', 'T', true)], outputs: [port('value', 'number', 'Value')], parameters: [], addable: true, bypass: 'passthrough' }),
  imageOperator({ id: 'convert.scalar-to-vec2', family: 'convert.scalar-vector', variant: 'vec2', label: 'Scalar to Vector 2', description: 'Replicates one scalar into two vector components.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('value', 'vec2', 'Vector')], parameters: [], addable: true }),
  imageOperator({ id: 'convert.scalar-to-rgb', label: 'Scalar to RGB', description: 'Replicates one scalar into three RGB components.',
    inputs: [port('value', 'number', 'Value', true)], outputs: [port('rgb', 'rgb', 'RGB')], parameters: [], addable: true }),
  // Read-only migration definitions. migrateImageOperatorGraph removes them before canonical persistence/compilation.
  imageOperator({ id: 'image.rgb-split', label: 'Legacy Split RGB + Alpha', description: 'Migrates to vector.split.rgba.',
    inputs: [port('image', 'image', 'Image', true)], outputs: [port('rgb', 'rgb', 'RGB'), port('alpha', 'alpha', 'Alpha')], parameters: [], addable: false }),
  imageOperator({ id: 'image.rgb-combine', label: 'Legacy Combine RGB + Alpha', description: 'Migrates to vector.combine.rgba.',
    inputs: [port('rgb', 'rgb', 'RGB', true), port('alpha', 'alpha', 'Alpha', true)], outputs: [port('image', 'image', 'Image')], parameters: [], addable: false }),
  imageOperator({ id: 'color.invert.rgb', label: 'Legacy RGB Invert', description: 'Migrates to scalar one, RGB splat and typed subtract.',
    inputs: [port('rgb', 'rgb', 'RGB', true)], outputs: [port('rgb', 'rgb', 'RGB')], parameters: [], addable: false, bypass: 'mute' }),
  imageOperator({ id: 'image.output', label: 'Image Output', description: 'Selects the image produced by this local graph.',
    inputs: [port('image', 'image', 'Image', true)], outputs: [], parameters: [], addable: false }),
];
