export const FLASHBOARD_PROMPT_REFINER_MODEL = 'gpt-5.5';
export const FLASHBOARD_PROMPT_REFINER_OPENAI_RESPONSES_URL = 'https://api.openai.com/v1/responses';
export const FLASHBOARD_PROMPT_REFINER_MAX_REFERENCE_IMAGE_EDGE = 1280;
export const FLASHBOARD_PROMPT_REFINER_REFERENCE_IMAGE_QUALITY = 0.88;
