export const TIMELINE_SPEECH_MAX_WORDS = 100_000 as const;
export const TIMELINE_SPEECH_SNAPSHOT_MAX_SEGMENTS = 2_000 as const;
export const TIMELINE_SPEECH_SNAPSHOT_MAX_TEXT_CHARACTERS = 100_000 as const;
export const TIMELINE_SPEECH_TOOL_DEFAULT_PAGE_WORDS = 1_000 as const;
export const TIMELINE_SPEECH_TOOL_MAX_PAGE_WORDS = 5_000 as const;
