// Surface Bind on the GPU (CPU reference: clothSurface.ts bindToCloth and strandFrames.ts
// packStrandPoints). The rest curves stay on the GPU; each frame only the simulated cloth grid is
// uploaded. bindPoints first applies Thread Along when enabled (threadAlong.ts) and the Yarn
// Profile radius fields (strandRadiusScale, generated by strandFieldShader.ts in place of the
// field marker below), then places every rest point on the bicubic (Catmull-Rom) sheet and lifts it
// along the sheet normal and leaves the radius scale in the frame slot; StrandFrames.wgsl then
// writes arc length, rotation-minimizing frames and tangents.

struct BindParams {
  columns: u32,
  rows: u32,
  strands: u32,
  points: u32,
  size: vec2f,      // rest sheet width and height
  height: f32,      // Surface Bind height scale
  dispatchWidth: u32,
  threadEnabled: u32,
  progress: f32,    // Thread Along: uniform progress, clamped stagger, lift, lift length and settle
  stagger: f32,
  lift: f32,
  liftLength: f32,
  settle: f32,
};

/** Lift lengths the tip travels past the curve end (SETTLE_LENGTHS in threadAlong.ts). */
const SETTLE_LENGTHS = 4.0;
const PI = 3.141592653589793;

@group(0) @binding(0) var<uniform> bind: BindParams;
// x, y, z on the flat rest sheet and the yarn radius scale.
@group(0) @binding(1) var<storage, read> rest: array<vec4f>;
// (columns + 1) × (rows + 1) simulated positions, row-major from the bottom edge.
@group(0) @binding(2) var<storage, read> grid: array<f32>;
// First point and point count per strand.
@group(0) @binding(3) var<storage, read> strandRanges: array<vec2u>;
// Three vec4 per point: (position, arc length), (frame normal, radius scale), (tangent, strand index).
@group(0) @binding(4) var<storage, read_write> packed: array<vec4f>;
// Arc length along the rest curve and strand index per point.
@group(0) @binding(5) var<storage, read> restArcs: array<vec2f>;
// Values of the constants in the radius fields.
@group(0) @binding(6) var<storage, read> fieldConstants: array<f32>;

/** Curve context a radius field reads (curveFieldColumns.ts): Position, Curve Param, indices, counts. */
struct FieldContext {
  position: vec3f,
  curveU: f32,
  point: f32,
  strand: f32,
  points: f32,
  strands: f32,
};

//@strand-fields

fn gridNode(x: i32, y: i32) -> vec3f {
  let base = u32(y * i32(bind.columns + 1u) + x) * 3u;
  return vec3f(grid[base], grid[base + 1u], grid[base + 2u]);
}

/** Rows beyond the border continue linearly. */
fn gridColumn(x: i32, y: i32) -> vec3f {
  let rows = i32(bind.rows);
  if (y < 0) {
    return 2.0 * gridNode(x, 0) - gridNode(x, 1);
  }
  if (y > rows) {
    return 2.0 * gridNode(x, rows) - gridNode(x, rows - 1);
  }
  return gridNode(x, y);
}

/** Columns beyond the border continue linearly, as in sampleClothGrid. */
fn gridAt(x: i32, y: i32) -> vec3f {
  let columns = i32(bind.columns);
  if (x < 0) {
    return 2.0 * gridColumn(0, y) - gridColumn(1, y);
  }
  if (x > columns) {
    return 2.0 * gridColumn(columns, y) - gridColumn(columns - 1, y);
  }
  return gridColumn(x, y);
}

fn weights(t: f32) -> vec4f {
  let t2 = t * t;
  let t3 = t2 * t;
  return vec4f(-t3 + 2.0 * t2 - t, 3.0 * t3 - 5.0 * t2 + 2.0, -3.0 * t3 + 4.0 * t2 + t, t3 - t2) * 0.5;
}

fn slopes(t: f32) -> vec4f {
  let t2 = t * t;
  return vec4f(-3.0 * t2 + 4.0 * t - 1.0, 9.0 * t2 - 10.0 * t, -9.0 * t2 + 8.0 * t + 1.0, 3.0 * t2 - 2.0 * t) * 0.5;
}

@compute @workgroup_size(256)
fn bindPoints(@builtin(global_invocation_id) gid: vec3u) {
  let index = gid.x + gid.y * bind.dispatchWidth * 256u;
  if (index >= bind.points) {
    return;
  }
  var local = rest[index];
  let info = restArcs[index];
  let strand = u32(info.y);
  let range = strandRanges[strand];
  if (bind.threadEnabled == 1u) {
    // Pulled in behind a tip: hidden ahead of it, lifted along +Z and settling behind it.
    let total = restArcs[range.x + range.y - 1u].x;
    let progress = clamp((bind.progress - bind.stagger * f32(strand) / f32(bind.strands)) / (1.0 - bind.stagger), 0.0, 1.0);
    let behind = progress * (total + SETTLE_LENGTHS * bind.liftLength) - info.x;
    local.w = select(0.0, local.w, progress > 0.0 && behind >= 0.0);
    let x = max(-1.0, behind / bind.liftLength);
    local.z += bind.lift * select(exp(-bind.settle * x) * cos(0.5 * PI * x), 1.0 - bind.settle * x, x < 0.0);
  }
  // Yarn Profile radius fields read the pulled-in point, like the CPU stages after Thread Along.
  let pointInStrand = index - range.x;
  let curveU = select(0.0, f32(pointInStrand) / f32(range.y - 1u), range.y > 1u);
  local.w *= strandRadiusScale(FieldContext(local.xyz, curveU, f32(pointInStrand), f32(strand), f32(range.y), f32(bind.strands)));
  let columns = f32(bind.columns);
  let rows = f32(bind.rows);
  let u = (local.x / bind.size.x + 0.5) * columns;
  let v = (local.y / bind.size.y + 0.5) * rows;
  let cu = clamp(u, 0.0, columns);
  let cv = clamp(v, 0.0, rows);
  let i = min(i32(bind.columns) - 1, i32(floor(cu)));
  let j = min(i32(bind.rows) - 1, i32(floor(cv)));
  let wu = weights(cu - f32(i));
  let wv = weights(cv - f32(j));
  let su = slopes(cu - f32(i));
  let sv = slopes(cv - f32(j));
  var point = vec3f(0.0);
  var du = vec3f(0.0);
  var dv = vec3f(0.0);
  for (var b = 0; b < 4; b++) {
    for (var a = 0; a < 4; a++) {
      let value = gridAt(i - 1 + a, j - 1 + b);
      point += wu[a] * wv[b] * value;
      du += su[a] * wv[b] * value;
      dv += wu[a] * sv[b] * value;
    }
  }
  // Beyond the sheet the surface continues along its edge tangent.
  point += du * (u - cu) + dv * (v - cv);
  let normal = cross(du, dv);
  let length = sqrt(dot(normal, normal));
  let lift = local.z * bind.height / select(1.0, length, length > 0.0);
  packed[index * 3u] = vec4f(point + normal * lift, 0.0);
  packed[index * 3u + 1u] = vec4f(0.0, 0.0, 0.0, local.w);
}
